"""Method aggregate: state, status enum, errors, events, evolver, read repo.

Vertical slices that operate on this aggregate live under
`cora.recipe.features.<verb>_method/` and import from here for
state and event types.
"""

from cora.recipe.aggregates.method.events import (
    MethodDefined,
    MethodDeprecated,
    MethodEvent,
    MethodLaunchSpecUpdated,
    MethodParametersSchemaUpdated,
    MethodRequiredRoleAdded,
    MethodRequiredRoleRemoved,
    MethodVersioned,
    event_type_name,
    from_stored,
    to_payload,
)
from cora.recipe.aggregates.method.evolver import evolve, fold
from cora.recipe.aggregates.method.execution_pattern import ExecutionPattern
from cora.recipe.aggregates.method.launch_argv import (
    MissingLaunchParameterError,
    UnsafeLaunchUriError,
    build_argv,
)
from cora.recipe.aggregates.method.launch_spec import (
    ArgStyle,
    InvalidLaunchSpecError,
    LaunchArg,
    LaunchSpec,
    launch_spec_from_dict,
    launch_spec_to_dict,
    validate_launch_spec,
)
from cora.recipe.aggregates.method.parameters_validation import (
    InvalidMethodParametersSchemaError,
    validate_parameters_schema,
)
from cora.recipe.aggregates.method.read import (
    MethodLifecycleTimestamps,
    load_method,
    load_method_timestamps,
)
from cora.recipe.aggregates.method.state import (
    ITERATIVE_STOPPING_KEYS,
    METHOD_NAME_MAX_LENGTH,
    METHOD_NEEDED_SUPPLY_KIND_MAX_LENGTH,
    METHOD_VERSION_TAG_MAX_LENGTH,
    ROLE_NAME_MAX_LENGTH,
    ROLE_PORT_NAME_MAX_LENGTH,
    ROLE_PORT_SIGNAL_TYPE_MAX_LENGTH,
    InvalidMethodIterativeStoppingFieldError,
    InvalidMethodMonotoneQualityError,
    InvalidMethodNameError,
    InvalidMethodNeededSuppliesError,
    InvalidMethodVersionTagError,
    InvalidPortRequirementError,
    InvalidRoleNameError,
    InvalidRoleRequirementTargetError,
    Method,
    MethodAlreadyExistsError,
    MethodCannotDeprecateError,
    MethodCannotMutateRequiredRolesError,
    MethodCannotVersionError,
    MethodCapabilityExecutorMismatchError,
    MethodLaunchArgNotBooleanError,
    MethodLaunchArgUnknownParameterError,
    MethodName,
    MethodNotFoundError,
    MethodParametersNotSubsetError,
    MethodParametersSchemaDropsLaunchArgError,
    MethodRoleNameAlreadyDeclaredError,
    MethodRoleNameNotFoundError,
    MethodStatus,
    PortRequirement,
    RoleName,
    RoleRequirement,
    RoleRequirementBindingDuplicateError,
)

__all__ = [
    "ITERATIVE_STOPPING_KEYS",
    "METHOD_NAME_MAX_LENGTH",
    "METHOD_NEEDED_SUPPLY_KIND_MAX_LENGTH",
    "METHOD_VERSION_TAG_MAX_LENGTH",
    "ROLE_NAME_MAX_LENGTH",
    "ROLE_PORT_NAME_MAX_LENGTH",
    "ROLE_PORT_SIGNAL_TYPE_MAX_LENGTH",
    "ArgStyle",
    "ExecutionPattern",
    "InvalidLaunchSpecError",
    "InvalidMethodIterativeStoppingFieldError",
    "InvalidMethodMonotoneQualityError",
    "InvalidMethodNameError",
    "InvalidMethodNeededSuppliesError",
    "InvalidMethodParametersSchemaError",
    "InvalidMethodVersionTagError",
    "InvalidPortRequirementError",
    "InvalidRoleNameError",
    "InvalidRoleRequirementTargetError",
    "LaunchArg",
    "LaunchSpec",
    "Method",
    "MethodAlreadyExistsError",
    "MethodCannotDeprecateError",
    "MethodCannotMutateRequiredRolesError",
    "MethodCannotVersionError",
    "MethodCapabilityExecutorMismatchError",
    "MethodDefined",
    "MethodDeprecated",
    "MethodEvent",
    "MethodLaunchArgNotBooleanError",
    "MethodLaunchArgUnknownParameterError",
    "MethodLaunchSpecUpdated",
    "MethodLifecycleTimestamps",
    "MethodName",
    "MethodNotFoundError",
    "MethodParametersNotSubsetError",
    "MethodParametersSchemaDropsLaunchArgError",
    "MethodParametersSchemaUpdated",
    "MethodRequiredRoleAdded",
    "MethodRequiredRoleRemoved",
    "MethodRoleNameAlreadyDeclaredError",
    "MethodRoleNameNotFoundError",
    "MethodStatus",
    "MethodVersioned",
    "MissingLaunchParameterError",
    "PortRequirement",
    "RoleName",
    "RoleRequirement",
    "RoleRequirementBindingDuplicateError",
    "UnsafeLaunchUriError",
    "build_argv",
    "event_type_name",
    "evolve",
    "fold",
    "from_stored",
    "launch_spec_from_dict",
    "launch_spec_to_dict",
    "load_method",
    "load_method_timestamps",
    "to_payload",
    "validate_launch_spec",
    "validate_parameters_schema",
]
