"""Lock the no-em-dash rule on tracked src/cora and tests/ .py files.

Per the writing-style memory and CLAUDE.md hard rules: em dashes don't
belong in source. Substitute commas, colons, or rephrase. The repo
landed at 562 .py files carrying em-dashes before the rule grew teeth;
those files are pinned in ``EMDASH_ALLOWLIST`` and may be scrubbed in
follow-up commits. Files NOT in the allowlist must stay em-dash-free.

The allowlist is a ratchet: it can shrink as files are cleaned (drop
the entry when the last em-dash leaves the file), but it cannot grow.
A new file with em-dashes fails the test and forces the rule at write
time rather than at audit time.

Two complementary checks live here:

  1. ``test_no_em_dashes_in_tracked_python_files``: every tracked .py
     under src/cora and tests/ that is NOT in the allowlist must be
     em-dash-free.
  2. ``test_em_dash_allowlist_entries_actually_contain_em_dashes``: every
     entry in the allowlist must still have at least one em-dash,
     otherwise the entry is stale and should be removed (the meta-test
     that keeps the ratchet trustworthy).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from tests.architecture.conftest import tracked_python_files, tracked_test_files

if TYPE_CHECKING:
    from pathlib import Path


_API_ROOT_MARKER = "apps/api/"
_EM_DASH = "\u2014"


EMDASH_ALLOWLIST: frozenset[str] = frozenset(
    {
        "src/cora/access/aggregates/actor/events.py",
        "src/cora/access/aggregates/actor/evolver.py",
        "src/cora/access/features/__init__.py",
        "src/cora/access/features/deactivate_actor/command.py",
        "src/cora/access/features/deactivate_actor/handler.py",
        "src/cora/access/features/deactivate_actor/route.py",
        "src/cora/access/features/forget_actor/__init__.py",
        "src/cora/access/features/forget_actor/command.py",
        "src/cora/access/features/forget_actor/decider.py",
        "src/cora/access/features/forget_actor/handler.py",
        "src/cora/access/features/forget_actor/route.py",
        "src/cora/access/features/get_actor/query.py",
        "src/cora/access/features/get_actor/tool.py",
        "src/cora/access/features/list_actors/handler.py",
        "src/cora/access/features/list_actors/query.py",
        "src/cora/access/features/list_actors/route.py",
        "src/cora/access/features/register_actor/command.py",
        "src/cora/access/features/register_actor/decider.py",
        "src/cora/access/features/register_actor/handler.py",
        "src/cora/access/features/register_actor/route.py",
        "src/cora/access/projections/summary.py",
        "src/cora/access/routes.py",
        "src/cora/access/wire.py",
        "src/cora/agent/_projections.py",
        "src/cora/agent/_subscribers.py",
        "src/cora/agent/aggregates/agent/events.py",
        "src/cora/agent/aggregates/agent/evolver.py",
        "src/cora/agent/aggregates/agent/read.py",
        "src/cora/agent/aggregates/agent/state.py",
        "src/cora/agent/features/define_agent/handler.py",
        "src/cora/agent/features/deprecate_agent/decider.py",
        "src/cora/agent/features/deprecate_agent/handler.py",
        "src/cora/agent/features/get_agent/handler.py",
        "src/cora/agent/features/get_agent/route.py",
        "src/cora/agent/features/get_agent/tool.py",
        "src/cora/agent/features/promote_caution_proposal/decider.py",
        "src/cora/agent/projections/agent.py",
        "src/cora/agent/prompts/caution_drafter.py",
        "src/cora/api/main.py",
        "src/cora/api/middleware.py",
        "src/cora/api/protected_resource_metadata.py",
        "src/cora/calibration/__init__.py",
        "src/cora/calibration/_calibration_dtos.py",
        "src/cora/calibration/aggregates/calibration/evolver.py",
        "src/cora/calibration/aggregates/calibration/read.py",
        "src/cora/calibration/aggregates/calibration/state.py",
        "src/cora/calibration/features/append_calibration_revision/command.py",
        "src/cora/calibration/features/append_calibration_revision/handler.py",
        "src/cora/calibration/features/define_calibration/command.py",
        "src/cora/calibration/features/define_calibration/handler.py",
        "src/cora/calibration/features/get_calibration/query.py",
        "src/cora/calibration/features/list_calibrations/query.py",
        "src/cora/calibration/quantities/__init__.py",
        "src/cora/calibration/wire.py",
        "src/cora/caution/features/list_cautions/route.py",
        "src/cora/data/aggregates/dataset/__init__.py",
        "src/cora/data/aggregates/dataset/events.py",
        "src/cora/data/aggregates/dataset/evolver.py",
        "src/cora/data/aggregates/dataset/state.py",
        "src/cora/data/features/demote_dataset/command.py",
        "src/cora/data/features/promote_dataset/command.py",
        "src/cora/data/features/promote_dataset/decider.py",
        "src/cora/data/features/promote_dataset/handler.py",
        "src/cora/data/features/register_dataset/decider.py",
        "src/cora/decision/aggregates/decision/evolver.py",
        "src/cora/decision/aggregates/decision/state.py",
        "src/cora/decision/features/list_decisions/query.py",
        "src/cora/equipment/_asset_update_handler.py",
        "src/cora/equipment/aggregates/asset/events.py",
        "src/cora/equipment/aggregates/asset/evolver.py",
        "src/cora/equipment/aggregates/asset/settings_validation.py",
        "src/cora/equipment/aggregates/asset/state.py",
        "src/cora/equipment/aggregates/family/affordance.py",
        "src/cora/equipment/aggregates/family/evolver.py",
        "src/cora/equipment/aggregates/family/read.py",
        "src/cora/equipment/aggregates/family/state.py",
        "src/cora/equipment/features/activate_asset/command.py",
        "src/cora/equipment/features/add_asset_family/command.py",
        "src/cora/equipment/features/add_asset_family/handler.py",
        "src/cora/equipment/features/add_asset_family/tool.py",
        "src/cora/equipment/features/add_asset_port/command.py",
        "src/cora/equipment/features/decommission_asset/command.py",
        "src/cora/equipment/features/define_family/command.py",
        "src/cora/equipment/features/define_family/handler.py",
        "src/cora/equipment/features/degrade_asset/command.py",
        "src/cora/equipment/features/deprecate_family/command.py",
        "src/cora/equipment/features/deprecate_family/handler.py",
        "src/cora/equipment/features/deprecate_family/route.py",
        "src/cora/equipment/features/enter_asset_maintenance/command.py",
        "src/cora/equipment/features/fault_asset/command.py",
        "src/cora/equipment/features/get_asset/handler.py",
        "src/cora/equipment/features/get_asset/query.py",
        "src/cora/equipment/features/get_asset/route.py",
        "src/cora/equipment/features/get_asset/tool.py",
        "src/cora/equipment/features/get_asset_integration_view/handler.py",
        "src/cora/equipment/features/get_asset_integration_view/query.py",
        "src/cora/equipment/features/get_asset_integration_view/tool.py",
        "src/cora/equipment/features/get_asset_integration_view/view.py",
        "src/cora/equipment/features/get_family/handler.py",
        "src/cora/equipment/features/get_family/query.py",
        "src/cora/equipment/features/get_family/tool.py",
        "src/cora/equipment/features/list_assets/query.py",
        "src/cora/equipment/features/register_asset/handler.py",
        "src/cora/equipment/features/relocate_asset/command.py",
        "src/cora/equipment/features/relocate_asset/decider.py",
        "src/cora/equipment/features/relocate_asset/handler.py",
        "src/cora/equipment/features/remove_asset_family/command.py",
        "src/cora/equipment/features/remove_asset_family/route.py",
        "src/cora/equipment/features/remove_asset_port/command.py",
        "src/cora/equipment/features/restore_asset/command.py",
        "src/cora/equipment/features/update_asset_settings/__init__.py",
        "src/cora/equipment/features/update_asset_settings/command.py",
        "src/cora/equipment/features/update_asset_settings/decider.py",
        "src/cora/equipment/features/update_asset_settings/handler.py",
        "src/cora/equipment/features/update_asset_settings/route.py",
        "src/cora/equipment/features/update_family_settings_schema/command.py",
        "src/cora/equipment/features/version_family/command.py",
        "src/cora/equipment/features/version_family/decider.py",
        "src/cora/equipment/features/version_family/handler.py",
        "src/cora/equipment/routes.py",
        "src/cora/infrastructure/adapters/introspection_token_verifier.py",
        "src/cora/infrastructure/adapters/jwt_token_verifier.py",
        "src/cora/infrastructure/adapters/postgres_profile_store.py",
        "src/cora/infrastructure/auth/__init__.py",
        "src/cora/infrastructure/auth/bearer_auth_middleware.py",
        "src/cora/infrastructure/auth/build_idp_registry.py",
        "src/cora/infrastructure/auth/config.py",
        "src/cora/infrastructure/auth/exception_handlers.py",
        "src/cora/infrastructure/auth/idp_registry.py",
        "src/cora/infrastructure/config.py",
        "src/cora/infrastructure/event_envelope.py",
        "src/cora/infrastructure/evolver.py",
        "src/cora/infrastructure/idempotency.py",
        "src/cora/infrastructure/idempotency_pruner.py",
        "src/cora/infrastructure/kernel.py",
        "src/cora/infrastructure/list_query.py",
        "src/cora/infrastructure/logging.py",
        "src/cora/infrastructure/mcp_principal.py",
        "src/cora/infrastructure/observability/__init__.py",
        "src/cora/infrastructure/observability/correlation.py",
        "src/cora/infrastructure/observability/log_processor.py",
        "src/cora/infrastructure/observability/provider.py",
        "src/cora/infrastructure/ports/__init__.py",
        "src/cora/infrastructure/ports/authorize.py",
        "src/cora/infrastructure/ports/caution_lookup.py",
        "src/cora/infrastructure/ports/clock.py",
        "src/cora/infrastructure/ports/event_publisher.py",
        "src/cora/infrastructure/ports/event_store.py",
        "src/cora/infrastructure/ports/idempotency_store.py",
        "src/cora/infrastructure/ports/llm.py",
        "src/cora/infrastructure/ports/profile_store.py",
        "src/cora/infrastructure/ports/signer.py",
        "src/cora/infrastructure/ports/token_verifier.py",
        "src/cora/infrastructure/projection/bookmark.py",
        "src/cora/infrastructure/projection/drain.py",
        "src/cora/infrastructure/projection/handler.py",
        "src/cora/infrastructure/projection/wakeup.py",
        "src/cora/infrastructure/projection/worker.py",
        "src/cora/infrastructure/routing.py",
        "src/cora/infrastructure/update_handler.py",
        "src/cora/operation/__init__.py",
        "src/cora/operation/features/register_procedure/command.py",
        "src/cora/operation/routes.py",
        "src/cora/recipe/_method_update_handler.py",
        "src/cora/recipe/_plan_update_handler.py",
        "src/cora/recipe/_practice_update_handler.py",
        "src/cora/recipe/aggregates/__init__.py",
        "src/cora/recipe/aggregates/capability/events.py",
        "src/cora/recipe/aggregates/capability/evolver.py",
        "src/cora/recipe/aggregates/capability/executor_shape.py",
        "src/cora/recipe/aggregates/capability/read.py",
        "src/cora/recipe/aggregates/capability/state.py",
        "src/cora/recipe/aggregates/method/events.py",
        "src/cora/recipe/aggregates/method/evolver.py",
        "src/cora/recipe/aggregates/method/read.py",
        "src/cora/recipe/aggregates/method/state.py",
        "src/cora/recipe/aggregates/plan/events.py",
        "src/cora/recipe/aggregates/plan/evolver.py",
        "src/cora/recipe/aggregates/plan/read.py",
        "src/cora/recipe/aggregates/plan/state.py",
        "src/cora/recipe/aggregates/plan/wires_validation.py",
        "src/cora/recipe/aggregates/practice/events.py",
        "src/cora/recipe/aggregates/practice/read.py",
        "src/cora/recipe/aggregates/practice/state.py",
        "src/cora/recipe/features/add_plan_wire/command.py",
        "src/cora/recipe/features/add_plan_wire/context.py",
        "src/cora/recipe/features/define_capability/command.py",
        "src/cora/recipe/features/define_capability/handler.py",
        "src/cora/recipe/features/define_method/command.py",
        "src/cora/recipe/features/define_method/decider.py",
        "src/cora/recipe/features/define_method/handler.py",
        "src/cora/recipe/features/define_method/route.py",
        "src/cora/recipe/features/define_plan/command.py",
        "src/cora/recipe/features/define_plan/context.py",
        "src/cora/recipe/features/define_plan/decider.py",
        "src/cora/recipe/features/define_plan/handler.py",
        "src/cora/recipe/features/define_practice/command.py",
        "src/cora/recipe/features/define_practice/handler.py",
        "src/cora/recipe/features/deprecate_capability/command.py",
        "src/cora/recipe/features/deprecate_method/command.py",
        "src/cora/recipe/features/deprecate_method/route.py",
        "src/cora/recipe/features/deprecate_plan/command.py",
        "src/cora/recipe/features/deprecate_plan/route.py",
        "src/cora/recipe/features/deprecate_practice/command.py",
        "src/cora/recipe/features/deprecate_practice/route.py",
        "src/cora/recipe/features/get_capability/query.py",
        "src/cora/recipe/features/get_capability/route.py",
        "src/cora/recipe/features/get_method/handler.py",
        "src/cora/recipe/features/get_method/query.py",
        "src/cora/recipe/features/get_method/route.py",
        "src/cora/recipe/features/get_method/tool.py",
        "src/cora/recipe/features/get_plan/handler.py",
        "src/cora/recipe/features/get_plan/query.py",
        "src/cora/recipe/features/get_plan/tool.py",
        "src/cora/recipe/features/get_practice/handler.py",
        "src/cora/recipe/features/get_practice/query.py",
        "src/cora/recipe/features/remove_plan_wire/command.py",
        "src/cora/recipe/features/remove_plan_wire/decider.py",
        "src/cora/recipe/features/update_method_parameters_schema/command.py",
        "src/cora/recipe/features/update_method_parameters_schema/decider.py",
        "src/cora/recipe/features/update_plan_default_parameters/command.py",
        "src/cora/recipe/features/update_plan_default_parameters/decider.py",
        "src/cora/recipe/features/update_plan_default_parameters/handler.py",
        "src/cora/recipe/features/update_plan_default_parameters/route.py",
        "src/cora/recipe/features/version_capability/command.py",
        "src/cora/recipe/features/version_capability/handler.py",
        "src/cora/recipe/features/version_method/command.py",
        "src/cora/recipe/features/version_plan/command.py",
        "src/cora/recipe/features/version_practice/command.py",
        "src/cora/recipe/projections/method.py",
        "src/cora/recipe/projections/plan.py",
        "src/cora/recipe/projections/practice.py",
        "src/cora/recipe/routes.py",
        "src/cora/recipe/wire.py",
        "src/cora/run/__init__.py",
        "src/cora/run/_run_update_handler.py",
        "src/cora/run/aggregates/run/entries.py",
        "src/cora/run/aggregates/run/events.py",
        "src/cora/run/aggregates/run/evolver.py",
        "src/cora/run/aggregates/run/parameters_validation.py",
        "src/cora/run/aggregates/run/state.py",
        "src/cora/run/features/abort_run/command.py",
        "src/cora/run/features/adjust_run/command.py",
        "src/cora/run/features/adjust_run/handler.py",
        "src/cora/run/features/append_observations/command.py",
        "src/cora/run/features/complete_run/command.py",
        "src/cora/run/features/get_run/query.py",
        "src/cora/run/features/hold_run/command.py",
        "src/cora/run/features/resume_run/command.py",
        "src/cora/run/features/start_run/command.py",
        "src/cora/run/features/start_run/decider.py",
        "src/cora/run/features/start_run/handler.py",
        "src/cora/run/features/start_run/route.py",
        "src/cora/run/features/stop_run/command.py",
        "src/cora/run/features/stop_run/decider.py",
        "src/cora/run/features/truncate_run/handler.py",
        "src/cora/run/wire.py",
        "src/cora/shared/bounded_text.py",
        "src/cora/shared/json_merge_patch.py",
        "src/cora/shared/json_schema_subset.py",
        "src/cora/shared/json_schema_validation.py",
        "src/cora/shared/logbook.py",
        "src/cora/subject/aggregates/subject/evolver.py",
        "src/cora/subject/aggregates/subject/state.py",
        "src/cora/subject/features/discard_subject/command.py",
        "src/cora/subject/features/dismount_subject/command.py",
        "src/cora/subject/features/get_subject/handler.py",
        "src/cora/subject/features/get_subject/query.py",
        "src/cora/subject/features/get_subject/tool.py",
        "src/cora/subject/features/list_subjects/query.py",
        "src/cora/subject/features/measure_subject/command.py",
        "src/cora/subject/features/measure_subject/decider.py",
        "src/cora/subject/features/mount_subject/command.py",
        "src/cora/subject/features/register_subject/command.py",
        "src/cora/subject/features/register_subject/handler.py",
        "src/cora/subject/features/remove_subject/command.py",
        "src/cora/subject/features/return_subject/command.py",
        "src/cora/subject/features/store_subject/command.py",
        "src/cora/subject/features/store_subject/decider.py",
        "src/cora/subject/projections/summary.py",
        "src/cora/subject/routes.py",
        "src/cora/subject/wire.py",
        "src/cora/supply/aggregates/supply/events.py",
        "src/cora/supply/aggregates/supply/state.py",
        "src/cora/supply/features/degrade_supply/command.py",
        "src/cora/supply/features/get_supply/handler.py",
        "src/cora/supply/features/get_supply/query.py",
        "src/cora/supply/features/mark_supply_available/command.py",
        "src/cora/supply/features/mark_supply_recovering/command.py",
        "src/cora/supply/features/mark_supply_unavailable/command.py",
        "src/cora/supply/features/register_supply/handler.py",
        "src/cora/supply/features/restore_supply/command.py",
        "src/cora/supply/projections/supply.py",
        "src/cora/supply/routes.py",
        "src/cora/supply/wire.py",
        "src/cora/trust/_bootstrap.py",
        "src/cora/trust/aggregates/conduit/entries.py",
        "src/cora/trust/aggregates/conduit/events.py",
        "src/cora/trust/aggregates/conduit/evolver.py",
        "src/cora/trust/aggregates/conduit/state.py",
        "src/cora/trust/aggregates/policy/events.py",
        "src/cora/trust/aggregates/policy/evolver.py",
        "src/cora/trust/aggregates/policy/state.py",
        "src/cora/trust/aggregates/surface/evolver.py",
        "src/cora/trust/aggregates/surface/state.py",
        "src/cora/trust/aggregates/surface/surface_kind.py",
        "src/cora/trust/aggregates/zone/state.py",
        "src/cora/trust/authorize.py",
        "src/cora/trust/features/define_conduit/command.py",
        "src/cora/trust/features/define_conduit/decider.py",
        "src/cora/trust/features/define_conduit/handler.py",
        "src/cora/trust/features/define_conduit/route.py",
        "src/cora/trust/features/define_policy/command.py",
        "src/cora/trust/features/define_policy/decider.py",
        "src/cora/trust/features/define_policy/handler.py",
        "src/cora/trust/features/define_policy/route.py",
        "src/cora/trust/features/define_surface/command.py",
        "src/cora/trust/features/define_surface/handler.py",
        "src/cora/trust/features/define_zone/command.py",
        "src/cora/trust/features/define_zone/decider.py",
        "src/cora/trust/features/define_zone/handler.py",
        "src/cora/trust/features/evaluate_policy/handler.py",
        "src/cora/trust/features/evaluate_policy/query.py",
        "src/cora/trust/features/evaluate_policy/route.py",
        "src/cora/trust/features/evaluate_policy/tool.py",
        "src/cora/trust/features/get_surface/query.py",
        "src/cora/trust/features/get_surface/route.py",
        "src/cora/trust/features/get_surface/tool.py",
        "src/cora/trust/features/list_permissions/__init__.py",
        "src/cora/trust/features/list_permissions/handler.py",
        "src/cora/trust/features/list_permissions/query.py",
        "src/cora/trust/features/list_permissions/route.py",
        "tests/_strategies.py",
        "tests/architecture/conftest.py",
        "tests/architecture/test_actor_events_carry_no_pii.py",
        "tests/architecture/test_actor_kind_sync.py",
        "tests/architecture/test_auth_principal_kind_sync.py",
        "tests/architecture/test_caution_invariants_module.py",
        "tests/architecture/test_domain_dataclasses_are_frozen.py",
        "tests/architecture/test_edge_auth_invariants.py",
        "tests/architecture/test_envelope_principal_id.py",
        "tests/architecture/test_error_handler_registration_scope.py",
        "tests/architecture/test_handler_accepts_surface_id.py",
        "tests/architecture/test_helper_naming_convention.py",
        "tests/architecture/test_no_em_dash_in_field_descriptions.py",
        "tests/architecture/test_routes_inject_surface_id.py",
        "tests/architecture/test_routes_tools_completeness.py",
        "tests/architecture/test_slice_test_coverage.py",
        "tests/architecture/test_state_error_naming_taxonomy.py",
        "tests/architecture/test_tools_inject_mcp_surface_id.py",
        "tests/conftest.py",
        "tests/contract/_helpers.py",
        "tests/contract/_mcp_helpers.py",
        "tests/contract/test_actors_endpoint.py",
        "tests/contract/test_add_plan_wire_endpoint.py",
        "tests/contract/test_add_remove_asset_port_endpoints.py",
        "tests/contract/test_body_size_limit.py",
        "tests/contract/test_complete_run_endpoint.py",
        "tests/contract/test_cross_principal_bola.py",
        "tests/contract/test_define_conduit_idempotency.py",
        "tests/contract/test_define_method_idempotency.py",
        "tests/contract/test_define_method_mcp_tool.py",
        "tests/contract/test_evaluate_policy_endpoint.py",
        "tests/contract/test_families_endpoint.py",
        "tests/contract/test_get_actor_endpoint.py",
        "tests/contract/test_idempotency_cached_error_replay.py",
        "tests/contract/test_idempotency_claim_lost_409.py",
        "tests/contract/test_list_actors_endpoint.py",
        "tests/contract/test_list_calibrations_endpoint.py",
        "tests/contract/test_plan_wire_authz_endpoint.py",
        "tests/contract/test_plans_endpoint.py",
        "tests/contract/test_policies_endpoint.py",
        "tests/contract/test_principal_header.py",
        "tests/contract/test_promote_caution_proposal_endpoint.py",
        "tests/contract/test_promote_dataset_endpoint.py",
        "tests/contract/test_protected_resource_metadata.py",
        "tests/contract/test_register_actor_differential.py",
        "tests/contract/test_register_dataset_endpoint.py",
        "tests/contract/test_runs_endpoint.py",
        "tests/contract/test_start_run_endpoint.py",
        "tests/contract/test_update_asset_settings_endpoint.py",
        "tests/e2e/conftest.py",
        "tests/integration/_helpers.py",
        "tests/integration/scenarios/_facility_fixture.py",
        "tests/integration/scenarios/test_2bm_agent_cost_overrun_pause.py",
        "tests/integration/scenarios/test_2bm_agent_tool_lifecycle.py",
        "tests/integration/scenarios/test_2bm_alignment_center.py",
        "tests/integration/scenarios/test_2bm_dismount_sample.py",
        "tests/integration/scenarios/test_2bm_facility.py",
        "tests/integration/scenarios/test_2bm_proposal_clearance.py",
        "tests/integration/scenarios/test_2bm_run_debriefer.py",
        "tests/integration/scenarios/test_2bm_run_debriefer_aborted.py",
        "tests/integration/scenarios/test_2bm_run_truncated_after_outage.py",
        "tests/integration/scenarios/test_2bm_streaming_tomography.py",
        "tests/integration/test_add_asset_family_handler_postgres.py",
        "tests/integration/test_add_run_to_campaign_postgres.py",
        "tests/integration/test_append_observations_handler_postgres.py",
        "tests/integration/test_capability_end_to_end_postgres.py",
        "tests/integration/test_caution_drafter_subscriber_postgres.py",
        "tests/integration/test_condition_transitions_handler_postgres.py",
        "tests/integration/test_define_calibration_handler_postgres.py",
        "tests/integration/test_define_plan_handler_postgres.py",
        "tests/integration/test_define_policy_handler_postgres.py",
        "tests/integration/test_define_practice_handler_postgres.py",
        "tests/integration/test_event_log_invariants.py",
        "tests/integration/test_event_store_contract.py",
        "tests/integration/test_list_assets_handler_postgres.py",
        "tests/integration/test_postgres_idempotency_store.py",
        "tests/integration/test_projection_wakeup_listen_notify_postgres.py",
        "tests/integration/test_projection_worker_lifespan_postgres.py",
        "tests/integration/test_projection_worker_postgres.py",
        "tests/integration/test_promote_caution_proposal_idempotency_postgres.py",
        "tests/integration/test_register_dataset_used_calibration_ids_postgres.py",
        "tests/integration/test_relocate_asset_handler_postgres.py",
        "tests/integration/test_seed_default_surfaces_and_v2_policy_postgres.py",
        "tests/integration/test_start_run_handler_postgres.py",
        "tests/integration/test_trust_authorize_cross_bc_postgres.py",
        "tests/integration/test_trust_authorize_gates_handlers_postgres.py",
        "tests/integration/test_trust_authorize_verdicts_postgres.py",
        "tests/integration/test_verify_bootstrap_seed_present_postgres.py",
        "tests/unit/_helpers.py",
        "tests/unit/access/test_actor_events_serialization_properties.py",
        "tests/unit/access/test_actor_evolver_properties.py",
        "tests/unit/access/test_actor_summary_projection.py",
        "tests/unit/access/test_deactivate_actor_decider_properties.py",
        "tests/unit/access/test_events.py",
        "tests/unit/access/test_forget_actor_handler.py",
        "tests/unit/access/test_register_actor_handler.py",
        "tests/unit/agent/test_caution_drafter_subscriber.py",
        "tests/unit/agent/test_promote_caution_proposal_handler.py",
        "tests/unit/agent/test_regenerate_run_debrief_handler.py",
        "tests/unit/auth/_helpers.py",
        "tests/unit/auth/test_bearer_auth_middleware.py",
        "tests/unit/auth/test_build_idp_registry.py",
        "tests/unit/auth/test_config.py",
        "tests/unit/auth/test_idp_registry.py",
        "tests/unit/auth/test_introspection_token_verifier.py",
        "tests/unit/auth/test_jwt_token_verifier.py",
        "tests/unit/auth/test_settings_env_load.py",
        "tests/unit/auth/test_verified_principal_properties.py",
        "tests/unit/calibration/test_calibration_evolver.py",
        "tests/unit/calibration/test_list_calibrations_handler.py",
        "tests/unit/caution/test_caution.py",
        "tests/unit/caution/test_caution_events.py",
        "tests/unit/caution/test_register_caution_decider.py",
        "tests/unit/data/test_dataset.py",
        "tests/unit/data/test_dataset_evolver.py",
        "tests/unit/data/test_intent_and_promotion_reason_vos.py",
        "tests/unit/data/test_register_dataset_decider.py",
        "tests/unit/equipment/test_activate_asset_decider.py",
        "tests/unit/equipment/test_activate_asset_handler.py",
        "tests/unit/equipment/test_affordance.py",
        "tests/unit/equipment/test_asset_events.py",
        "tests/unit/equipment/test_asset_evolver.py",
        "tests/unit/equipment/test_asset_settings_validation.py",
        "tests/unit/equipment/test_asset_summary_projection.py",
        "tests/unit/equipment/test_capability_settings_validation.py",
        "tests/unit/equipment/test_condition_slices_handlers.py",
        "tests/unit/equipment/test_decommission_asset_decider.py",
        "tests/unit/equipment/test_family_events.py",
        "tests/unit/equipment/test_family_evolver.py",
        "tests/unit/equipment/test_get_asset_handler.py",
        "tests/unit/equipment/test_get_family_handler.py",
        "tests/unit/equipment/test_register_asset_handler.py",
        "tests/unit/equipment/test_relocate_asset_handler.py",
        "tests/unit/equipment/test_update_asset_settings_decider.py",
        "tests/unit/equipment/test_update_family_settings_schema_decider.py",
        "tests/unit/equipment/test_version_family_decider.py",
        "tests/unit/infrastructure/test_mcp_principal.py",
        "tests/unit/infrastructure/test_routing.py",
        "tests/unit/observability/conftest.py",
        "tests/unit/observability/test_correlation.py",
        "tests/unit/observability/test_handler_spans_via_testclient.py",
        "tests/unit/observability/test_provider.py",
        "tests/unit/operation/test_procedure_events.py",
        "tests/unit/operation/test_procedure_evolver.py",
        "tests/unit/projection/test_registry.py",
        "tests/unit/recipe/test_add_plan_wire_decider.py",
        "tests/unit/recipe/test_define_plan_decider.py",
        "tests/unit/recipe/test_define_plan_handler.py",
        "tests/unit/recipe/test_event_type_cohabitation.py",
        "tests/unit/recipe/test_method_events.py",
        "tests/unit/recipe/test_method_needed_supplies.py",
        "tests/unit/recipe/test_method_parameters_validation.py",
        "tests/unit/recipe/test_plan_events.py",
        "tests/unit/recipe/test_plan_evolver.py",
        "tests/unit/recipe/test_plan_parameters_validation.py",
        "tests/unit/recipe/test_plan_wire_slices_handlers.py",
        "tests/unit/recipe/test_practice_events.py",
        "tests/unit/recipe/test_update_method_parameters_schema_subset.py",
        "tests/unit/recipe/test_update_plan_default_parameters_handler.py",
        "tests/unit/recipe/test_version_plan_content_hash.py",
        "tests/unit/run/test_abort_run_decider.py",
        "tests/unit/run/test_adjust_run_handler.py",
        "tests/unit/run/test_append_observations_handler.py",
        "tests/unit/run/test_complete_run_decider.py",
        "tests/unit/run/test_run.py",
        "tests/unit/run/test_run_events.py",
        "tests/unit/run/test_run_evolver.py",
        "tests/unit/run/test_run_parameters_validation.py",
        "tests/unit/run/test_observation_entries.py",
        "tests/unit/run/test_start_run_decider.py",
        "tests/unit/run/test_start_run_handler.py",
        "tests/unit/run/test_truncate_run_decider.py",
        "tests/unit/run/test_truncate_run_handler.py",
        "tests/unit/subject/test_measure_subject_decider.py",
        "tests/unit/subject/test_measure_subject_handler.py",
        "tests/unit/subject/test_mount_subject_decider.py",
        "tests/unit/subject/test_mount_subject_handler.py",
        "tests/unit/subject/test_remove_subject_decider.py",
        "tests/unit/subject/test_remove_subject_handler.py",
        "tests/unit/subject/test_return_subject_decider.py",
        "tests/unit/supply/test_supply.py",
        "tests/unit/supply/test_supply_summary_projection.py",
        "tests/unit/test_deps.py",
        "tests/unit/test_event_envelope.py",
        "tests/unit/test_event_store_property.py",
        "tests/unit/test_idempotency_decorator.py",
        "tests/unit/test_idempotency_pruner.py",
        "tests/unit/test_in_memory_event_store.py",
        "tests/unit/test_in_memory_idempotency_store.py",
        "tests/unit/test_json_schema_subset.py",
        "tests/unit/test_logbook.py",
        "tests/unit/test_route_defensive_409_handlers.py",
        "tests/unit/trust/test_conduit.py",
        "tests/unit/trust/test_conduit_events.py",
        "tests/unit/trust/test_conduit_evolver.py",
        "tests/unit/trust/test_define_policy_decider.py",
        "tests/unit/trust/test_evaluate_policy_handler.py",
        "tests/unit/trust/test_surface.py",
        "tests/unit/trust/test_surface_events.py",
        "tests/unit/trust/test_trust_authorize.py",
        "tests/unit/trust/test_zone_events.py",
        "tests/unit/trust/test_zone_evolver_properties.py",
    }
)


def _rel(path: Path) -> str:
    """Path relative to apps/api/, matching the allowlist's keying."""
    s = str(path)
    idx = s.rfind(_API_ROOT_MARKER)
    return s[idx + len(_API_ROOT_MARKER) :] if idx != -1 else s


@pytest.mark.architecture
def test_no_em_dashes_in_tracked_python_files() -> None:
    """Every tracked .py outside the allowlist is em-dash-free.

    The allowlist is the snapshot of files carrying em-dashes when the
    rule grew teeth. New files (and previously-clean files that grow
    em-dashes) fail here. Scrub a file by removing every em-dash in it,
    then dropping its entry from ``EMDASH_ALLOWLIST``; the meta-test
    will keep that drop honest.
    """
    violators: list[Path] = []
    for path in sorted(tracked_python_files() | tracked_test_files()):
        if _rel(path) in EMDASH_ALLOWLIST:
            continue
        text = path.read_text(encoding="utf-8")
        if _EM_DASH in text:
            violators.append(path)

    if not violators:
        return

    msg_lines = [
        f"Found em-dash in {len(violators)} tracked .py file(s) not in EMDASH_ALLOWLIST.",
        "Substitute commas, colons, or rephrase. See CLAUDE.md hard rules.",
        "",
    ]
    for path in violators[:20]:
        msg_lines.append(f"  {_rel(path)}")
    if len(violators) > 20:
        msg_lines.append(f"  ... and {len(violators) - 20} more")
    pytest.fail("\n".join(msg_lines))


@pytest.mark.architecture
def test_em_dash_allowlist_entries_actually_contain_em_dashes() -> None:
    """Every allowlist entry must still carry at least one em-dash.

    Catches stale entries (the file was scrubbed but the allowlist was
    not updated). Keeps the ratchet trustworthy: an entry that no
    longer points at a violation must be removed so the allowlist only
    ever shrinks.
    """
    tracked_by_rel = {_rel(p): p for p in tracked_python_files() | tracked_test_files()}
    stale: list[str] = []
    missing: list[str] = []
    for rel in sorted(EMDASH_ALLOWLIST):
        path = tracked_by_rel.get(rel)
        if path is None:
            missing.append(rel)
            continue
        text = path.read_text(encoding="utf-8")
        if _EM_DASH not in text:
            stale.append(rel)

    msg_lines: list[str] = []
    if missing:
        msg_lines.append(
            f"{len(missing)} EMDASH_ALLOWLIST entries reference files that no "
            "longer exist in the tracked .py set; remove them:"
        )
        msg_lines.extend(f"  {rel}" for rel in missing[:10])
        if len(missing) > 10:
            msg_lines.append(f"  ... and {len(missing) - 10} more")
    if stale:
        msg_lines.append(
            f"{len(stale)} EMDASH_ALLOWLIST entries no longer contain an em-dash "
            "(scrubbed without updating the allowlist); remove them:"
        )
        msg_lines.extend(f"  {rel}" for rel in stale[:10])
        if len(stale) > 10:
            msg_lines.append(f"  ... and {len(stale) - 10} more")
    if msg_lines:
        pytest.fail("\n".join(msg_lines))
