"""Procedure aggregate: state, status enum, errors, events, evolver, read repo, entries.

Vertical slices that operate on this aggregate live under
`cora.operation.features.<verb>_procedure/` and import from here for
state and event types.

Public surface: VOs + errors + events (genesis +
start/complete/abort/truncate + steps lazy-open envelope) + evolver +
load_procedure + per-step logbook entries (ActivityStore port +
InMemory + Postgres adapters + Activity dataclass) + projection.
"""

from cora.operation.aggregates.procedure.entries import (
    Activity,
    ActivityStore,
    InMemoryActivityStore,
    PostgresActivityStore,
)
from cora.operation.aggregates.procedure.events import (
    ProcedureAborted,
    ProcedureActivitiesLogbookOpened,
    ProcedureCompleted,
    ProcedureEvent,
    ProcedureHeld,
    ProcedureIterationEnded,
    ProcedureIterationStarted,
    ProcedureRegistered,
    ProcedureResumed,
    ProcedureStarted,
    ProcedureTruncated,
    RecipeExpansionRecorded,
    ResolvedStepsRecorded,
    event_type_name,
    from_stored,
    to_payload,
)
from cora.operation.aggregates.procedure.evolver import evolve, fold
from cora.operation.aggregates.procedure.read import (
    load_procedure,
    load_procedure_with_events,
)
from cora.operation.aggregates.procedure.state import (
    LOGBOOK_KIND_ACTIVITY,
    PROCEDURE_KIND_MAX_LENGTH,
    PROCEDURE_NAME_MAX_LENGTH,
    RECIPE_EXPANSION_STEP_MAX,
    STEP_KIND_VALUES,
    STEPS_LOGBOOK_SCHEMA,
    InvalidProcedureAbortReasonError,
    InvalidProcedureHoldReasonError,
    InvalidProcedureInterruptedAtError,
    InvalidProcedureIterationCapError,
    InvalidProcedureIterationEndReasonError,
    InvalidProcedureKindError,
    InvalidProcedureNameError,
    InvalidProcedureReEstablishmentBoundaryError,
    InvalidProcedureTruncateReasonError,
    InvalidRecipeBindingsError,
    InvalidStepKindError,
    Procedure,
    ProcedureAbortReason,
    ProcedureAlreadyExistsError,
    ProcedureBeamAvailabilityUnknownError,
    ProcedureBoundCapabilityDeprecatedError,
    ProcedureCannotAbortError,
    ProcedureCannotCompleteError,
    ProcedureCannotEndIterationError,
    ProcedureCannotHoldError,
    ProcedureCannotResumeError,
    ProcedureCannotStartError,
    ProcedureCannotStartIterationError,
    ProcedureCannotTruncateError,
    ProcedureCapabilityExecutorMismatchError,
    ProcedureEnclosureCoverageMismatchError,
    ProcedureHoldReason,
    ProcedureIterationLimitReachedError,
    ProcedureName,
    ProcedureNotFoundError,
    ProcedurePlanAssetDecommissionedError,
    ProcedureRequiresAvailableSupplyError,
    ProcedureRequiresOpenBeamShuttersError,
    ProcedureRequiresPermittedEnclosureError,
    ProcedureStatus,
    ProcedureStepsForbiddenForRecipeDrivenError,
    ProcedureStepsLogbookClosedError,
    ProcedureSupplyCoverageMismatchError,
    ProcedureTruncateReason,
    RecipeBindingsStaleAgainstCurrentCapabilityError,
    RecipeExpanderVersionMismatchError,
    RecipeExpansionDeterminismError,
    RecipeExpansionOverflowError,
    RecipeExpansionRecordNotFoundError,
    RecipeExpansionReplayMismatchError,
    ResolvedStepsRecordNotFoundError,
    StepKind,
    merge_actuation_kinds,
)

__all__ = [
    "LOGBOOK_KIND_ACTIVITY",
    "PROCEDURE_KIND_MAX_LENGTH",
    "PROCEDURE_NAME_MAX_LENGTH",
    "RECIPE_EXPANSION_STEP_MAX",
    "STEPS_LOGBOOK_SCHEMA",
    "STEP_KIND_VALUES",
    "Activity",
    "ActivityStore",
    "InMemoryActivityStore",
    "InvalidProcedureAbortReasonError",
    "InvalidProcedureHoldReasonError",
    "InvalidProcedureInterruptedAtError",
    "InvalidProcedureIterationCapError",
    "InvalidProcedureIterationEndReasonError",
    "InvalidProcedureKindError",
    "InvalidProcedureNameError",
    "InvalidProcedureReEstablishmentBoundaryError",
    "InvalidProcedureTruncateReasonError",
    "InvalidRecipeBindingsError",
    "InvalidStepKindError",
    "PostgresActivityStore",
    "Procedure",
    "ProcedureAbortReason",
    "ProcedureAborted",
    "ProcedureActivitiesLogbookOpened",
    "ProcedureAlreadyExistsError",
    "ProcedureBeamAvailabilityUnknownError",
    "ProcedureBoundCapabilityDeprecatedError",
    "ProcedureCannotAbortError",
    "ProcedureCannotCompleteError",
    "ProcedureCannotEndIterationError",
    "ProcedureCannotHoldError",
    "ProcedureCannotResumeError",
    "ProcedureCannotStartError",
    "ProcedureCannotStartIterationError",
    "ProcedureCannotTruncateError",
    "ProcedureCapabilityExecutorMismatchError",
    "ProcedureCompleted",
    "ProcedureEnclosureCoverageMismatchError",
    "ProcedureEvent",
    "ProcedureHeld",
    "ProcedureHoldReason",
    "ProcedureIterationEnded",
    "ProcedureIterationLimitReachedError",
    "ProcedureIterationStarted",
    "ProcedureName",
    "ProcedureNotFoundError",
    "ProcedurePlanAssetDecommissionedError",
    "ProcedureRegistered",
    "ProcedureRequiresAvailableSupplyError",
    "ProcedureRequiresOpenBeamShuttersError",
    "ProcedureRequiresPermittedEnclosureError",
    "ProcedureResumed",
    "ProcedureStarted",
    "ProcedureStatus",
    "ProcedureStepsForbiddenForRecipeDrivenError",
    "ProcedureStepsLogbookClosedError",
    "ProcedureSupplyCoverageMismatchError",
    "ProcedureTruncateReason",
    "ProcedureTruncated",
    "RecipeBindingsStaleAgainstCurrentCapabilityError",
    "RecipeExpanderVersionMismatchError",
    "RecipeExpansionDeterminismError",
    "RecipeExpansionOverflowError",
    "RecipeExpansionRecordNotFoundError",
    "RecipeExpansionRecorded",
    "RecipeExpansionReplayMismatchError",
    "ResolvedStepsRecordNotFoundError",
    "ResolvedStepsRecorded",
    "StepKind",
    "event_type_name",
    "evolve",
    "fold",
    "from_stored",
    "load_procedure",
    "load_procedure_with_events",
    "merge_actuation_kinds",
    "to_payload",
]
