"""Procedure aggregate: state, status enum, errors, events, evolver, read repo, entries.

Vertical slices that operate on this aggregate live under
`cora.operation.features.<verb>_procedure/` and import from here for
state and event types.

Public surface: VOs + errors + events (genesis +
start/complete/abort/truncate + steps lazy-open envelope) + evolver +
load_procedure + per-step logbook entries (ActivityStore port +
InMemory + Postgres adapters + Activity dataclass) + projection.
"""

from cora.operation.aggregates.procedure.entries import (
    Activity,
    ActivityStore,
    InMemoryActivityStore,
    PostgresActivityStore,
)
from cora.operation.aggregates.procedure.events import (
    ProcedureAborted,
    ProcedureActivitiesLogbookOpened,
    ProcedureCompleted,
    ProcedureEvent,
    ProcedureRegistered,
    ProcedureStarted,
    ProcedureTruncated,
    RecipeExpansionRecorded,
    event_type_name,
    from_stored,
    to_payload,
)
from cora.operation.aggregates.procedure.evolver import evolve, fold
from cora.operation.aggregates.procedure.read import (
    load_procedure,
    load_procedure_with_events,
)
from cora.operation.aggregates.procedure.state import (
    LOGBOOK_KIND_ACTIVITY,
    PROCEDURE_ABORT_REASON_MAX_LENGTH,
    PROCEDURE_KIND_MAX_LENGTH,
    PROCEDURE_NAME_MAX_LENGTH,
    PROCEDURE_TRUNCATE_REASON_MAX_LENGTH,
    RECIPE_EXPANSION_STEP_MAX,
    STEP_KIND_VALUES,
    STEPS_LOGBOOK_SCHEMA,
    InvalidProcedureAbortReasonError,
    InvalidProcedureInterruptedAtError,
    InvalidProcedureKindError,
    InvalidProcedureNameError,
    InvalidProcedureTruncateReasonError,
    InvalidRecipeBindingsError,
    InvalidStepKindError,
    Procedure,
    ProcedureAbortReason,
    ProcedureAlreadyExistsError,
    ProcedureBoundCapabilityDeprecatedError,
    ProcedureCannotAbortError,
    ProcedureCannotCompleteError,
    ProcedureCannotStartError,
    ProcedureCannotTruncateError,
    ProcedureCapabilityExecutorMismatchError,
    ProcedureEnclosureCoverageMismatchError,
    ProcedureName,
    ProcedureNotFoundError,
    ProcedurePlanAssetDecommissionedError,
    ProcedureRequiresAvailableSupplyError,
    ProcedureRequiresPermittedEnclosureError,
    ProcedureStatus,
    ProcedureStepsForbiddenForRecipeDrivenError,
    ProcedureStepsLogbookClosedError,
    ProcedureSupplyCoverageMismatchError,
    ProcedureTruncateReason,
    RecipeBindingsStaleAgainstCurrentCapabilityError,
    RecipeExpanderVersionMismatchError,
    RecipeExpansionDeterminismError,
    RecipeExpansionOverflowError,
    RecipeExpansionRecordNotFoundError,
    RecipeExpansionReplayMismatchError,
    StepKind,
)

__all__ = [
    "LOGBOOK_KIND_ACTIVITY",
    "PROCEDURE_ABORT_REASON_MAX_LENGTH",
    "PROCEDURE_KIND_MAX_LENGTH",
    "PROCEDURE_NAME_MAX_LENGTH",
    "PROCEDURE_TRUNCATE_REASON_MAX_LENGTH",
    "RECIPE_EXPANSION_STEP_MAX",
    "STEPS_LOGBOOK_SCHEMA",
    "STEP_KIND_VALUES",
    "Activity",
    "ActivityStore",
    "InMemoryActivityStore",
    "InvalidProcedureAbortReasonError",
    "InvalidProcedureInterruptedAtError",
    "InvalidProcedureKindError",
    "InvalidProcedureNameError",
    "InvalidProcedureTruncateReasonError",
    "InvalidRecipeBindingsError",
    "InvalidStepKindError",
    "PostgresActivityStore",
    "Procedure",
    "ProcedureAbortReason",
    "ProcedureAborted",
    "ProcedureActivitiesLogbookOpened",
    "ProcedureAlreadyExistsError",
    "ProcedureBoundCapabilityDeprecatedError",
    "ProcedureCannotAbortError",
    "ProcedureCannotCompleteError",
    "ProcedureCannotStartError",
    "ProcedureCannotTruncateError",
    "ProcedureCapabilityExecutorMismatchError",
    "ProcedureCompleted",
    "ProcedureEnclosureCoverageMismatchError",
    "ProcedureEvent",
    "ProcedureName",
    "ProcedureNotFoundError",
    "ProcedurePlanAssetDecommissionedError",
    "ProcedureRegistered",
    "ProcedureRequiresAvailableSupplyError",
    "ProcedureRequiresPermittedEnclosureError",
    "ProcedureStarted",
    "ProcedureStatus",
    "ProcedureStepsForbiddenForRecipeDrivenError",
    "ProcedureStepsLogbookClosedError",
    "ProcedureSupplyCoverageMismatchError",
    "ProcedureTruncateReason",
    "ProcedureTruncated",
    "RecipeBindingsStaleAgainstCurrentCapabilityError",
    "RecipeExpanderVersionMismatchError",
    "RecipeExpansionDeterminismError",
    "RecipeExpansionOverflowError",
    "RecipeExpansionRecordNotFoundError",
    "RecipeExpansionRecorded",
    "RecipeExpansionReplayMismatchError",
    "StepKind",
    "event_type_name",
    "evolve",
    "fold",
    "from_stored",
    "load_procedure",
    "load_procedure_with_events",
    "to_payload",
]
