"""Agent aggregate: state, status FSM, VOs, errors, events, evolver, read repo.

Vertical slices that operate on this aggregate live under
`cora.agent.features.<verb>_agent/` and import from here for state
and event types.

Public surface: status FSM + VOs + ModelRef + errors + events +
evolver + load_agent.

Ships the foundation (define + version + deprecate + get); no
projection or list slice yet (deferred until per-kind active-agent
queries surface).
"""

from cora.agent.aggregates.agent.events import (
    AgentBudgetRevised,
    AgentDefined,
    AgentDeprecated,
    AgentEvent,
    AgentResumed,
    AgentSuspended,
    AgentToolGranted,
    AgentToolRevoked,
    AgentVersioned,
    deserialize_model_ref,
    event_type_name,
    from_stored,
    serialize_model_ref,
    to_payload,
)
from cora.agent.aggregates.agent.evolver import evolve, fold
from cora.agent.aggregates.agent.read import (
    AgentLifecycleTimestamps,
    load_agent,
    load_agent_timestamps,
)
from cora.agent.aggregates.agent.state import (
    AGENT_CANONICAL_URI_MAX_LENGTH,
    AGENT_CAPABILITIES_MAX_COUNT,
    AGENT_CAPABILITY_MAX_LENGTH,
    AGENT_DESCRIPTION_MAX_LENGTH,
    AGENT_KIND_MAX_LENGTH,
    AGENT_NAME_MAX_LENGTH,
    AGENT_TOOL_NAME_MAX_LENGTH,
    AGENT_TOOLS_MAX_COUNT,
    AGENT_VERSION_MAX_LENGTH,
    MODEL_REF_MODEL_MAX_LENGTH,
    MODEL_REF_PROVIDER_MAX_LENGTH,
    MODEL_REF_SNAPSHOT_PIN_MAX_LENGTH,
    Agent,
    AgentAlreadyExistsError,
    AgentBudget,
    AgentCannotDeprecateError,
    AgentCannotGrantToolError,
    AgentCannotResumeError,
    AgentCannotReviseBudgetError,
    AgentCannotRevokeToolError,
    AgentCannotSuspendError,
    AgentCannotVersionError,
    AgentCanonicalUri,
    AgentCapability,
    AgentDeactivatedError,
    AgentDeprecationReason,
    AgentDescription,
    AgentKind,
    AgentName,
    AgentNotFoundError,
    AgentNotSeededError,
    AgentStatus,
    AgentSuspensionReason,
    AgentVersion,
    InvalidAgentBudgetError,
    InvalidAgentCanonicalUriError,
    InvalidAgentCapabilitiesError,
    InvalidAgentCapabilityError,
    InvalidAgentDeprecationReasonError,
    InvalidAgentDescriptionError,
    InvalidAgentKindError,
    InvalidAgentNameError,
    InvalidAgentSuspensionReasonError,
    InvalidAgentToolsError,
    InvalidAgentVersionError,
    InvalidModelRefError,
    InvalidToolNameError,
    ModelRef,
    ToolName,
)

__all__ = [
    "AGENT_CANONICAL_URI_MAX_LENGTH",
    "AGENT_CAPABILITIES_MAX_COUNT",
    "AGENT_CAPABILITY_MAX_LENGTH",
    "AGENT_DESCRIPTION_MAX_LENGTH",
    "AGENT_KIND_MAX_LENGTH",
    "AGENT_NAME_MAX_LENGTH",
    "AGENT_TOOLS_MAX_COUNT",
    "AGENT_TOOL_NAME_MAX_LENGTH",
    "AGENT_VERSION_MAX_LENGTH",
    "MODEL_REF_MODEL_MAX_LENGTH",
    "MODEL_REF_PROVIDER_MAX_LENGTH",
    "MODEL_REF_SNAPSHOT_PIN_MAX_LENGTH",
    "Agent",
    "AgentAlreadyExistsError",
    "AgentBudget",
    "AgentBudgetRevised",
    "AgentCannotDeprecateError",
    "AgentCannotGrantToolError",
    "AgentCannotResumeError",
    "AgentCannotReviseBudgetError",
    "AgentCannotRevokeToolError",
    "AgentCannotSuspendError",
    "AgentCannotVersionError",
    "AgentCanonicalUri",
    "AgentCapability",
    "AgentDeactivatedError",
    "AgentDefined",
    "AgentDeprecated",
    "AgentDeprecationReason",
    "AgentDescription",
    "AgentEvent",
    "AgentKind",
    "AgentLifecycleTimestamps",
    "AgentName",
    "AgentNotFoundError",
    "AgentNotSeededError",
    "AgentResumed",
    "AgentStatus",
    "AgentSuspended",
    "AgentSuspensionReason",
    "AgentToolGranted",
    "AgentToolRevoked",
    "AgentVersion",
    "AgentVersioned",
    "InvalidAgentBudgetError",
    "InvalidAgentCanonicalUriError",
    "InvalidAgentCapabilitiesError",
    "InvalidAgentCapabilityError",
    "InvalidAgentDeprecationReasonError",
    "InvalidAgentDescriptionError",
    "InvalidAgentKindError",
    "InvalidAgentNameError",
    "InvalidAgentSuspensionReasonError",
    "InvalidAgentToolsError",
    "InvalidAgentVersionError",
    "InvalidModelRefError",
    "InvalidToolNameError",
    "ModelRef",
    "ToolName",
    "deserialize_model_ref",
    "event_type_name",
    "evolve",
    "fold",
    "from_stored",
    "load_agent",
    "load_agent_timestamps",
    "serialize_model_ref",
    "to_payload",
]
