"""Model aggregate: state, status enum, errors, events, evolver.

Vertical slices that operate on this aggregate live under
`cora.equipment.features.<verb>_model/` and import from here for
state and event types.
"""

from cora.equipment.aggregates.model.events import (
    ModelDefined,
    ModelDeprecated,
    ModelEvent,
    ModelFamilyAdded,
    ModelFamilyRemoved,
    ModelVersioned,
    event_type_name,
    from_stored,
    to_payload,
)
from cora.equipment.aggregates.model.evolver import evolve, fold
from cora.equipment.aggregates.model.state import (
    MANUFACTURER_IDENTIFIER_MAX_LENGTH,
    MANUFACTURER_NAME_MAX_LENGTH,
    MODEL_DEPRECATION_REASON_MAX_LENGTH,
    MODEL_NAME_MAX_LENGTH,
    MODEL_PART_NUMBER_MAX_LENGTH,
    MODEL_VERSION_TAG_MAX_LENGTH,
    InvalidDeclaredFamiliesError,
    InvalidManufacturerIdentifierError,
    InvalidManufacturerIdentifierPairingError,
    InvalidManufacturerNameError,
    InvalidModelDeprecationReasonError,
    InvalidModelNameError,
    InvalidModelVersionTagError,
    InvalidPartNumberError,
    Manufacturer,
    ManufacturerIdentifier,
    ManufacturerIdentifierType,
    ManufacturerName,
    Model,
    ModelAlreadyExistsError,
    ModelCannotDeprecateError,
    ModelCannotVersionError,
    ModelDeprecationReason,
    ModelFamilyAlreadyPresentError,
    ModelFamilyNotPresentError,
    ModelName,
    ModelNotFoundError,
    ModelStatus,
    ModelVersionTag,
    PartNumber,
)

__all__ = [
    "MANUFACTURER_IDENTIFIER_MAX_LENGTH",
    "MANUFACTURER_NAME_MAX_LENGTH",
    "MODEL_DEPRECATION_REASON_MAX_LENGTH",
    "MODEL_NAME_MAX_LENGTH",
    "MODEL_PART_NUMBER_MAX_LENGTH",
    "MODEL_VERSION_TAG_MAX_LENGTH",
    "InvalidDeclaredFamiliesError",
    "InvalidManufacturerIdentifierError",
    "InvalidManufacturerIdentifierPairingError",
    "InvalidManufacturerNameError",
    "InvalidModelDeprecationReasonError",
    "InvalidModelNameError",
    "InvalidModelVersionTagError",
    "InvalidPartNumberError",
    "Manufacturer",
    "ManufacturerIdentifier",
    "ManufacturerIdentifierType",
    "ManufacturerName",
    "Model",
    "ModelAlreadyExistsError",
    "ModelCannotDeprecateError",
    "ModelCannotVersionError",
    "ModelDefined",
    "ModelDeprecated",
    "ModelDeprecationReason",
    "ModelEvent",
    "ModelFamilyAdded",
    "ModelFamilyAlreadyPresentError",
    "ModelFamilyNotPresentError",
    "ModelFamilyRemoved",
    "ModelName",
    "ModelNotFoundError",
    "ModelStatus",
    "ModelVersionTag",
    "ModelVersioned",
    "PartNumber",
    "event_type_name",
    "evolve",
    "fold",
    "from_stored",
    "to_payload",
]
