"""DoiMinter port: mints PIDINST Property 1 persistent identifiers.

Operator-facing surface for assigning a PIDINST v1.0 Property 1
persistent identifier (DOI or Handle) at an external authority such
as DataCite or Handle.net. The port returns the assigned
`PersistentIdentifier` (scheme + value) to the calling slice. The
slice does NOT need to know whether the value was operator-supplied,
auto-generated by the authority, or stitched from a configured prefix
plus suffix; that is the adapter's concern.

The DataCite mint posture (F.2 production adapter) uses PUT /dois/{id}
upsert semantics with the DOI string as the dedup key (F5.2): retrying
the same (prefix, suffix) pair is safe at the wire because DataCite
treats the PUT as idempotent on the DOI string. The CORA caller does
not pass an Idempotency-Key header (F5.1).

The Stub adapter (ships in F.1) returns a deterministic test
identifier built from a fixed test prefix plus the supplied suffix
(or a UUID-based suffix when none was supplied), and never errors.

The production adapter (deferred to F.2) calls DataCite and may raise
`PersistentIdentifierMintError` on:
  - HTTP 4xx (operator error, scheme misuse, malformed DOI)
  - HTTP 5xx after exhausting the 429 backoff schedule
  - Network failures
  - DataCite repository account misconfiguration

The error class is a single catch-all per
[[project-genesis-error-classes]] (don't hoist; per-BC); the route
maps it to 502.
"""

from typing import Protocol

from cora.shared.identifier import (
    PersistentIdentifier,
    PersistentIdentifierScheme,
)


class PersistentIdentifierMintError(Exception):
    """The external mint authority failed to assign a persistent identifier.

    Wraps:
      - HTTP 4xx from DataCite (operator error, malformed suffix, etc.)
      - HTTP 5xx from DataCite after the 429 backoff schedule exhausted
      - Network failures (timeout, DNS failure, TLS handshake failure)
      - Adapter configuration failure (missing credentials at call time)

    Per [[project-genesis-error-classes]] don't-hoist convention: lives
    in the Equipment BC, not in `cora.infrastructure.errors`. The route
    maps to HTTP 502 (Bad Gateway) because this is upstream-port
    failure, NOT a domain-state conflict (which would be 409). The Stub
    adapter never raises this; F.2's production adapter is the sole
    source.
    """

    def __init__(self, *, scheme: PersistentIdentifierScheme, reason: str) -> None:
        super().__init__(
            f"Failed to mint persistent identifier under scheme {scheme.value}: {reason}"
        )
        self.scheme = scheme
        self.reason = reason


class DoiMinter(Protocol):
    """Mints a persistent identifier at an external authority."""

    async def mint(
        self,
        *,
        scheme: PersistentIdentifierScheme,
        suffix: str | None,
    ) -> PersistentIdentifier:
        """Mint a persistent identifier under the given scheme.

        `suffix` is the operator-supplied local part (without prefix);
        when None the adapter asks the authority to auto-generate.

        Returns the full `PersistentIdentifier` (scheme + value) where
        value is the authority-assigned global string (for example
        "10.5281/zenodo.1234567" for a DOI).

        Raises `PersistentIdentifierMintError` on any external failure;
        the route maps to HTTP 502.
        """
        ...
