"""Generated redaction dispositions. DO NOT EDIT BY HAND.

Regenerate with `make record-dispositions`;
`tests/architecture/test_record_dispositions_drift.py` fails until you do.

One entry per event type, one disposition per declared field, resolved
from the field's real type by `tools/gen_record_dispositions.py`. The
vocabulary:

    keep:enum:<Name>       closed value set, provably reviewable. The
                           enum is NAMED because a human signs off the
                           value set, and swapping one enum for another
                           must read as drift.
    keep:closed:<Name>       a value object every one of whose fields is
                           closed by construction (a fixed charset and
                           length, a closed literal set), kept WHOLE
                           rather than resolved field by field. See
                           `cora.shared.closed_value.ClosedValueObject`.
    keep:number            int / float / bool
    keep:time              datetime
    token:uuid             replaced with a per-export random surrogate
    drop:text              free text, no finite range, dropped by default
    drop:opaque            a dict with no declared keys, nothing to
                           allowlist
    by-value               the slot is polymorphic across scalars and
                           objects, so no static answer exists. Apply the
                           tier-2 leaf rule at export time: numbers and
                           booleans keep, UUID-shaped strings token,
                           other strings drop.

A nested mapping is a value object recursed into. A mapping whose sole
key is `[]` is a fixed-length heterogeneous tuple, and its value lists
one disposition per position.

Redaction iterates the STORED payload's keys and looks each up here. A
key absent from its event's entry is dropped; an event type absent from
this table aborts the export. The canonical hash of this mapping is the
redaction profile hash recorded in the export manifest.

A handful of entries are keyed on the WIRE key a field is actually
stored under rather than its dataclass field name, per
`gen_record_dispositions.py`'s `_OVERRIDE_WIRE_KEYS`: the two never
disagree about what ships, only about which name this table's lookup
uses to find it.
"""

from typing import Any

DISPOSITIONS: dict[str, dict[str, Any]] = {
    "AcquisitionRecorded": {
        "acquisition_id": "token:uuid",
        "captured_at": "keep:time",
        "dataset_id": "token:uuid",
        "evidence": {
            "captured_at_raw": "drop:text",
            "captured_at_source": "keep:enum:CapturedAtSource",
            "checksum_computer_kind": "drop:text",
            "commanded_dark_count": "keep:number",
            "commanded_flat_count": "keep:number",
            "commanded_projection_count": "keep:number",
            "dark_count": "keep:number",
            "dropped_frame_count": "keep:number",
            "flat_count": "keep:number",
            "invalid_count": "keep:number",
            "projection_angle_count": "keep:number",
            "projection_angle_first": "keep:number",
            "projection_angle_last": "keep:number",
            "projection_count": "keep:number",
            "reader_kind": "drop:text",
        },
        "occurred_at": "keep:time",
        "producing_asset_id": "token:uuid",
        "producing_run_id": "token:uuid",
        "recorded_by": "token:uuid",
        "settings": "drop:opaque",
    },
    "ActorDeactivated": {"actor_id": "token:uuid", "occurred_at": "keep:time"},
    "ActorProfileForgotten": {"actor_id": "token:uuid", "occurred_at": "keep:time"},
    "ActorReactivated": {"actor_id": "token:uuid", "occurred_at": "keep:time"},
    "ActorRegisteredV2": {
        "actor_id": "token:uuid",
        "kind": "keep:enum:ActorKind",
        "occurred_at": "keep:time",
    },
    "AgentBudgetUpdated": {
        "agent_id": "token:uuid",
        "daily_token_cap": "keep:number",
        "monthly_usd_cap": "keep:number",
        "occurred_at": "keep:time",
    },
    "AgentDefined": {
        "agent_id": "token:uuid",
        "canonical_uri": "drop:text",
        "capabilities": "drop:text",
        "daily_token_cap": "keep:number",
        "description": "drop:text",
        "kind": "drop:text",
        "model_ref": {"model": "drop:text", "provider": "drop:text", "snapshot_pin": "drop:text"},
        "monthly_usd_cap": "keep:number",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "prompt_template_id": "token:uuid",
        "tools": "drop:text",
        "version": "drop:text",
    },
    "AgentDeprecated": {
        "agent_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "AgentResumed": {
        "agent_id": "token:uuid",
        "occurred_at": "keep:time",
        "resumed_by": "token:uuid",
    },
    "AgentSuspended": {
        "agent_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "suspended_by": "token:uuid",
    },
    "AgentTargetPlanUpdated": {
        "agent_id": "token:uuid",
        "occurred_at": "keep:time",
        "target_plan_id": "token:uuid",
    },
    "AgentToolGranted": {
        "agent_id": "token:uuid",
        "occurred_at": "keep:time",
        "tool_name": "drop:text",
    },
    "AgentToolRevoked": {
        "agent_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "tool_name": "drop:text",
    },
    "AgentVersioned": {
        "agent_id": "token:uuid",
        "occurred_at": "keep:time",
        "version": "drop:text",
    },
    "AllocationActivated": {
        "activated_by": "token:uuid",
        "allocation_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "AllocationCeilingUpdated": {
        "allocation_id": "token:uuid",
        "ceiling_usd": "keep:number",
        "occurred_at": "keep:time",
    },
    "AllocationGranted": {
        "allocation_id": "token:uuid",
        "campaign_id": "token:uuid",
        "ceiling_usd": "keep:number",
        "granted_by": "token:uuid",
        "note": "drop:text",
        "occurred_at": "keep:time",
    },
    "AllocationSealed": {
        "allocation_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "sealed_by": "token:uuid",
        "spent_usd": "keep:number",
    },
    "AllocationVoided": {
        "allocation_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "AssemblyDefined": {
        "assembly_id": "token:uuid",
        "content_hash": "drop:text",
        "drawing": {
            "number": "drop:text",
            "revision": "drop:text",
            "system": "keep:enum:DrawingSystem",
        },
        "name": {"value": "drop:text"},
        "occurred_at": "keep:time",
        "parameter_overrides_schema": "drop:opaque",
        "presents_as": "token:uuid",
        "required_slots": {
            "cardinality": "keep:enum:SlotCardinality",
            "default_placement": {
                "parent_frame_id": "token:uuid",
                "reference_surface": "keep:enum:ReferenceSurface",
                "rx": "keep:number",
                "ry": "keep:number",
                "rz": "keep:number",
                "tol_rx": "keep:number",
                "tol_ry": "keep:number",
                "tol_rz": "keep:number",
                "tol_x": "keep:number",
                "tol_y": "keep:number",
                "tol_z": "keep:number",
                "units": "keep:enum:UnitSystem",
                "x": "keep:number",
                "y": "keep:number",
                "z": "keep:number",
            },
            "default_settings": "drop:opaque",
            "required_family_ids": "token:uuid",
            "slot_name": {"value": "drop:text"},
        },
        "required_sub_assemblies": {
            "content_hash": "drop:text",
            "slot_name": {"value": "drop:text"},
            "sub_assembly_id": "token:uuid",
        },
        "required_wires": {
            "source_port_name": "drop:text",
            "source_slot_name": "drop:text",
            "target_port_name": "drop:text",
            "target_slot_name": "drop:text",
        },
        "version": "drop:text",
    },
    "AssemblyDeprecated": {
        "assembly_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "AssemblyPresentsAsAdded": {
        "assembly_id": "token:uuid",
        "occurred_at": "keep:time",
        "role_id": "token:uuid",
    },
    "AssemblyPresentsAsRemoved": {
        "assembly_id": "token:uuid",
        "occurred_at": "keep:time",
        "role_id": "token:uuid",
    },
    "AssemblyVersioned": {
        "assembly_id": "token:uuid",
        "content_hash": "drop:text",
        "drawing": {
            "number": "drop:text",
            "revision": "drop:text",
            "system": "keep:enum:DrawingSystem",
        },
        "name": {"value": "drop:text"},
        "occurred_at": "keep:time",
        "parameter_overrides_schema": "drop:opaque",
        "presents_as": "token:uuid",
        "previous_content_hash": "drop:text",
        "required_slots": {
            "cardinality": "keep:enum:SlotCardinality",
            "default_placement": {
                "parent_frame_id": "token:uuid",
                "reference_surface": "keep:enum:ReferenceSurface",
                "rx": "keep:number",
                "ry": "keep:number",
                "rz": "keep:number",
                "tol_rx": "keep:number",
                "tol_ry": "keep:number",
                "tol_rz": "keep:number",
                "tol_x": "keep:number",
                "tol_y": "keep:number",
                "tol_z": "keep:number",
                "units": "keep:enum:UnitSystem",
                "x": "keep:number",
                "y": "keep:number",
                "z": "keep:number",
            },
            "default_settings": "drop:opaque",
            "required_family_ids": "token:uuid",
            "slot_name": {"value": "drop:text"},
        },
        "required_sub_assemblies": {
            "content_hash": "drop:text",
            "slot_name": {"value": "drop:text"},
            "sub_assembly_id": "token:uuid",
        },
        "required_wires": {
            "source_port_name": "drop:text",
            "source_slot_name": "drop:text",
            "target_port_name": "drop:text",
            "target_slot_name": "drop:text",
        },
        "version": "drop:text",
    },
    "AssetActivated": {"asset_id": "token:uuid", "occurred_at": "keep:time"},
    "AssetAlternateIdentifierAdded": {
        "alternate_identifier": {"kind": "keep:enum:AlternateIdentifierKind", "value": "drop:text"},
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "AssetAlternateIdentifierRemoved": {
        "alternate_identifier": {"kind": "keep:enum:AlternateIdentifierKind", "value": "drop:text"},
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "AssetAttachedToFixture": {
        "asset_id": "token:uuid",
        "fixture_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "AssetDecommissioned": {
        "asset_id": "token:uuid",
        "decommissioned_by": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "AssetDegraded": {"asset_id": "token:uuid", "occurred_at": "keep:time", "reason": "drop:text"},
    "AssetDetachedFromFixture": {
        "asset_id": "token:uuid",
        "fixture_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "AssetFacilityCodeAssigned": {
        "asset_id": "token:uuid",
        "assigned_by": "token:uuid",
        "facility_code": {"value": "drop:text"},
        "occurred_at": "keep:time",
    },
    "AssetFamilyAdded": {
        "asset_id": "token:uuid",
        "family_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "AssetFamilyRemoved": {
        "asset_id": "token:uuid",
        "family_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "AssetFaulted": {"asset_id": "token:uuid", "occurred_at": "keep:time", "reason": "drop:text"},
    "AssetMaintenanceEntered": {"asset_id": "token:uuid", "occurred_at": "keep:time"},
    "AssetMaintenanceExited": {"asset_id": "token:uuid", "occurred_at": "keep:time"},
    "AssetOwnerAdded": {
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
        "owner": {
            "contact": {"value": "drop:text"},
            "identifier": {"value": "drop:text"},
            "identifier_type": {"value": "drop:text"},
            "name": {"value": "drop:text"},
        },
    },
    "AssetOwnerRemoved": {
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
        "owner_name": {"value": "drop:text"},
    },
    "AssetPartitionRuleUpdated": {
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
        "partition_rule": {
            "aggregator_kind": "keep:enum:AggregatorKind",
            "calibration_id": "token:uuid",
            "calibration_revision_id": "token:uuid",
            "constituent_count": "keep:number",
            "extrapolation_kind": "keep:enum:ExtrapolationKind",
            "gain": "keep:number",
            "interpolation_kind": "keep:enum:InterpolationKind",
            "invertible": "keep:number",
            "kind": "keep:enum",
            "offset": "keep:number",
            "partition_kind": "keep:enum:PartitionKind",
            "partition_parameters": {"[]": ["drop:text", "keep:number"]},
            "readback_aggregator_kind": "keep:enum:ReadbackAggregatorKind",
            "residual_tolerance_limit": "keep:number",
            "singularity_threshold": "keep:number",
            "solver_id": "drop:text",
            "solver_transport_kind": "keep:enum:SolverTransportKind",
            "solver_version": "drop:text",
            "unit_in": "drop:text",
            "unit_out": "drop:text",
        },
    },
    "AssetPersistentIdAssigned": {
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
        "persistent_id_scheme": "drop:text",
        "persistent_id_value": "drop:text",
    },
    "AssetPortAdded": {
        "asset_id": "token:uuid",
        "direction": "drop:text",
        "occurred_at": "keep:time",
        "port_name": "drop:text",
        "signal_type": "drop:text",
    },
    "AssetPortRemoved": {
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
        "port_name": "drop:text",
    },
    "AssetRegistered": {
        "alternate_identifiers": {
            "kind": "keep:enum:AlternateIdentifierKind",
            "value": "drop:text",
        },
        "asset_id": "token:uuid",
        "commissioned_by": "token:uuid",
        "controller_id": "token:uuid",
        "drawing": {
            "number": "drop:text",
            "revision": "drop:text",
            "system": "keep:enum:DrawingSystem",
        },
        "facility_code": {"value": "drop:text"},
        "located_in_enclosure_id": "token:uuid",
        "model_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "owners": {
            "contact": {"value": "drop:text"},
            "identifier": {"value": "drop:text"},
            "identifier_type": {"value": "drop:text"},
            "name": {"value": "drop:text"},
        },
        "parent_id": "token:uuid",
        "tier": "drop:text",
    },
    "AssetRelocated": {
        "asset_id": "token:uuid",
        "from_parent_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "to_parent_id": "token:uuid",
    },
    "AssetRestored": {"asset_id": "token:uuid", "occurred_at": "keep:time", "reason": "drop:text"},
    "AssetSettingsUpdated": {
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
        "settings": "drop:opaque",
    },
    "AttestationRecorded": {
        "attestation_id": "token:uuid",
        "attested_by": "token:uuid",
        "dataset_id": "token:uuid",
        "distribution_id": "token:uuid",
        "evidence": "drop:opaque",
        "kind": "drop:text",
        "occurred_at": "keep:time",
        "outcome": "drop:text",
    },
    "CalibrationDefined": {
        "calibration_id": "token:uuid",
        "defined_by": "token:uuid",
        "description": "drop:text",
        "occurred_at": "keep:time",
        "operating_point": "drop:opaque",
        "quantity": "drop:text",
        "target_id": "token:uuid",
    },
    "CalibrationRevisionAppended": {
        "asserted_by": "token:uuid",
        "calibration_id": "token:uuid",
        "content_hash": "drop:text",
        "decided_by_decision_id": "token:uuid",
        "established_at": "keep:time",
        "established_by": "token:uuid",
        "occurred_at": "keep:time",
        "revision_id": "token:uuid",
        "source_dataset_id": "token:uuid",
        "source_procedure_id": "token:uuid",
        "status": "keep:enum:CalibrationStatus",
        "supersedes_revision_id": "token:uuid",
        "value": "drop:opaque",
    },
    "CalibrationRevisionPublished": {
        "calibration_id": "token:uuid",
        "occurred_at": "keep:time",
        "outbound_permit_id": "token:uuid",
        "publication_status": "drop:text",
        "published_at": "keep:time",
        "published_by": "token:uuid",
        "receipt_id": "token:uuid",
        "revision_id": "token:uuid",
        "signature_bytes_hex": "drop:text",
        "signature_envelope_kind": "drop:text",
        "signature_kid": "drop:text",
        "signing_version": "drop:text",
    },
    "CampaignAbandoned": {
        "campaign_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "CampaignClosed": {"campaign_id": "token:uuid", "occurred_at": "keep:time"},
    "CampaignHeld": {
        "campaign_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "CampaignRegistered": {
        "campaign_id": "token:uuid",
        "description": "drop:text",
        "external_id": "drop:text",
        "external_refs": {"scheme": "drop:text", "value": "drop:text"},
        "intent": "drop:text",
        "lead_actor_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "subject_id": "token:uuid",
        "tags": "drop:text",
    },
    "CampaignResumed": {"campaign_id": "token:uuid", "occurred_at": "keep:time"},
    "CampaignRunAdded": {
        "campaign_id": "token:uuid",
        "occurred_at": "keep:time",
        "run_id": "token:uuid",
    },
    "CampaignRunRemoved": {
        "campaign_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "run_id": "token:uuid",
    },
    "CampaignStarted": {"campaign_id": "token:uuid", "occurred_at": "keep:time"},
    "CampaignSteeringDeclared": {
        "campaign_id": "token:uuid",
        "objective": {
            "kind": "keep:enum:SteeringObjectiveKind",
            "target_measurement_name": "drop:text",
            "target_value": "keep:number",
        },
        "occurred_at": "keep:time",
        "space": {
            "axes": {
                "choices": "drop:opaque",
                "lower": "keep:number",
                "name": "drop:text",
                "upper": "keep:number",
            }
        },
    },
    "CapabilityDefined": {
        "capability_id": "token:uuid",
        "code": "drop:text",
        "description": "drop:text",
        "executor_shapes": "keep:enum:ExecutorShape",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "parameters_schema": "drop:opaque",
        "required_affordances": "keep:enum:Affordance",
    },
    "CapabilityDeprecated": {
        "capability_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "replaced_by_capability_id": "token:uuid",
    },
    "CapabilitySuggestedRolesUpdated": {
        "capability_id": "token:uuid",
        "occurred_at": "keep:time",
        "suggested_role_ids": "token:uuid",
    },
    "CapabilityVersioned": {
        "capability_id": "token:uuid",
        "description": "drop:text",
        "executor_shapes": "keep:enum:ExecutorShape",
        "occurred_at": "keep:time",
        "parameters_schema": "drop:opaque",
        "required_affordances": "keep:enum:Affordance",
        "version_tag": "drop:text",
    },
    "CautionAcknowledgement": {
        "category": "drop:text",
        "caution_id": "token:uuid",
        "severity": "drop:text",
        "target_id": "token:uuid",
        "target_kind": "drop:text",
        "text_excerpt": "drop:text",
        "workaround_excerpt": "drop:text",
    },
    "CautionRegistered": {
        "authored_by": "token:uuid",
        "category": "drop:text",
        "caution_id": "token:uuid",
        "expires_at": "keep:time",
        "occurred_at": "keep:time",
        "parent_id": "token:uuid",
        "propagate_to_children": "keep:number",
        "severity": "drop:text",
        "tags": "drop:text",
        "target": {"asset_id": "token:uuid", "procedure_id": "token:uuid"},
        "text": "drop:text",
        "workaround": "drop:text",
    },
    "CautionRetired": {
        "caution_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "CautionSuperseded": {
        "caution_id": "token:uuid",
        "occurred_at": "keep:time",
        "superseded_by_caution_id": "token:uuid",
    },
    "ClearanceActivated": {"clearance_id": "token:uuid", "occurred_at": "keep:time"},
    "ClearanceApproved": {
        "clearance_id": "token:uuid",
        "occurred_at": "keep:time",
        "valid_from": "keep:time",
        "valid_until": "keep:time",
    },
    "ClearanceExpired": {
        "clearance_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "ClearanceRegistered": {
        "bindings": "drop:opaque",
        "clearance_id": "token:uuid",
        "declarations": "drop:opaque",
        "external_id": "drop:text",
        "facility_code": "drop:text",
        "occurred_at": "keep:time",
        "parent_id": "token:uuid",
        "risk_band": "drop:text",
        "template_code": "drop:text",
        "template_id": "token:uuid",
        "title": "drop:text",
        "valid_from": "keep:time",
        "valid_until": "keep:time",
    },
    "ClearanceRejected": {
        "clearance_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "ClearanceReviewStarted": {
        "clearance_id": "token:uuid",
        "first_reviewer_role": "drop:text",
        "occurred_at": "keep:time",
    },
    "ClearanceReviewStepAppended": {
        "clearance_id": "token:uuid",
        "decided_at": "keep:time",
        "decided_by": "token:uuid",
        "decision": "drop:text",
        "notes": "drop:text",
        "occurred_at": "keep:time",
        "role": "drop:text",
        "step_index": "keep:number",
    },
    "ClearanceSubmitted": {"clearance_id": "token:uuid", "occurred_at": "keep:time"},
    "ClearanceSuperseded": {
        "by_clearance_id": "token:uuid",
        "clearance_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "ClearanceTemplateActivated": {
        "activated_by": "token:uuid",
        "occurred_at": "keep:time",
        "template_id": "token:uuid",
    },
    "ClearanceTemplateDefined": {
        "code": "drop:text",
        "defined_by": "token:uuid",
        "external_ref": "drop:text",
        "facility_code": "drop:text",
        "occurred_at": "keep:time",
        "supersedes_template_id": "token:uuid",
        "template_id": "token:uuid",
        "title": "drop:text",
        "version": "keep:number",
    },
    "ClearanceTemplateDeprecated": {
        "deprecated_by": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "template_id": "token:uuid",
    },
    "ClearanceTemplateVersioned": {
        "new_version": "keep:number",
        "occurred_at": "keep:time",
        "supersedes_template_id": "token:uuid",
        "template_id": "token:uuid",
        "versioned_by": "token:uuid",
    },
    "ClearanceTemplateWithdrawn": {
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "template_id": "token:uuid",
        "withdrawn_by": "token:uuid",
    },
    "ConduitDefined": {
        "conduit_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "source_zone_id": "token:uuid",
        "target_zone_id": "token:uuid",
    },
    "ConduitLogbookClosed": {
        "conduit_id": "token:uuid",
        "logbook_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "ConduitLogbookOpened": {
        "conduit_id": "token:uuid",
        "kind": "drop:text",
        "logbook_id": "token:uuid",
        "occurred_at": "keep:time",
        "schema": {"description": "drop:text", "fields": "drop:opaque"},
    },
    "CredentialRegistered": {
        "audience": "drop:text",
        "credential_id": "token:uuid",
        "expires_at": "keep:time",
        "facility_id": {"value": "drop:text"},
        "occurred_at": "keep:time",
        "public_material_ref": "drop:text",
        "purpose": "keep:enum:CredentialPurpose",
        "registered_by": "token:uuid",
        "secret_ref": "drop:text",
    },
    "CredentialRevoked": {
        "credential_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "revoked_by": "token:uuid",
    },
    "CredentialRotationAborted": {
        "credential_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "rotation_aborted_by": "token:uuid",
    },
    "CredentialRotationCompleted": {
        "credential_id": "token:uuid",
        "occurred_at": "keep:time",
        "rotation_completed_by": "token:uuid",
    },
    "CredentialRotationStarted": {
        "credential_id": "token:uuid",
        "occurred_at": "keep:time",
        "pending_public_material_ref": "drop:text",
        "pending_secret_ref": "drop:text",
        "rotation_started_by": "token:uuid",
    },
    "DatasetDemoted": {
        "dataset_id": "token:uuid",
        "demoted_by": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "DatasetDiscarded": {
        "dataset_id": "token:uuid",
        "discarded_by": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "DatasetPromoted": {
        "dataset_id": "token:uuid",
        "occurred_at": "keep:time",
        "promoted_by": "token:uuid",
        "reason": "drop:text",
    },
    "DatasetRegistered": {
        "byte_size": "keep:number",
        "checksum": "keep:closed:DatasetChecksum",
        "dataset_id": "token:uuid",
        "derived_from": "token:uuid",
        "encoding": {"conforms_to": "drop:text", "media_type": "drop:text"},
        "intent": "keep:enum:Intent",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "producing_actuation_kind": "drop:text",
        "producing_procedure_id": "token:uuid",
        "producing_run_end_state": "drop:text",
        "producing_run_id": "token:uuid",
        "registered_by": "token:uuid",
        "subject_id": "token:uuid",
        "uri": "drop:text",
        "used_calibration_ids": "token:uuid",
    },
    "DecisionDebriefRequested": {
        "debriefer_agent_id": "token:uuid",
        "debriefer_kind": "drop:text",
        "occurred_at": "keep:time",
        "run_id": "token:uuid",
        "terminal_event_id": "token:uuid",
    },
    "DecisionLogbookClosed": {
        "decision_id": "token:uuid",
        "logbook_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "DecisionLogbookOpened": {
        "decision_id": "token:uuid",
        "kind": "drop:text",
        "logbook_id": "token:uuid",
        "occurred_at": "keep:time",
        "schema": {"description": "drop:text", "fields": "drop:opaque"},
    },
    "DecisionRated": {
        "comment": "drop:text",
        "confidence_at_rating": "keep:number",
        "decision_id": "token:uuid",
        "occurred_at": "keep:time",
        "rated_at": "keep:time",
        "rated_by": "token:uuid",
        "rating": "keep:enum:DecisionRating",
    },
    "DecisionRegistered": {
        "alternatives": "drop:text",
        "choice": "drop:text",
        "confidence": "keep:number",
        "confidence_source": "keep:enum:DecisionConfidenceSource",
        "context": "drop:text",
        "decided_by": "token:uuid",
        "decision_id": "token:uuid",
        "inputs": "drop:opaque",
        "occurred_at": "keep:time",
        "override_kind": "keep:enum",
        "parent_id": "token:uuid",
        "reasoning": "drop:text",
        "reasoning_signature": "drop:text",
        "rule": "drop:text",
    },
    "DistributionDiscarded": {
        "discarded_by": "token:uuid",
        "distribution_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "DistributionRegistered": {
        "access_protocol": "keep:enum:AccessProtocol",
        "byte_size": "keep:number",
        "checksum": "keep:closed:DatasetChecksum",
        "dataset_id": "token:uuid",
        "distribution_id": "token:uuid",
        "encoding": {"conforms_to": "drop:text", "media_type": "drop:text"},
        "occurred_at": "keep:time",
        "registered_by": "token:uuid",
        "supply_id": "token:uuid",
        "uri": "drop:text",
    },
    "EditionDatasetAdded": {
        "added_by": "token:uuid",
        "dataset_id": "token:uuid",
        "edition_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "EditionDatasetRemoved": {
        "dataset_id": "token:uuid",
        "edition_id": "token:uuid",
        "occurred_at": "keep:time",
        "removed_by": "token:uuid",
    },
    "EditionPublished": {
        "edition_id": "token:uuid",
        "external_pid_scheme": "drop:text",
        "external_pid_value": "drop:text",
        "occurred_at": "keep:time",
        "published_by": "token:uuid",
        "published_content_hash": "drop:text",
    },
    "EditionRegistered": {
        "creators": "drop:opaque",
        "dataset_ids": "token:uuid",
        "edition_id": "token:uuid",
        "kind": "drop:text",
        "license": "drop:text",
        "occurred_at": "keep:time",
        "publication_year": "keep:number",
        "publisher_facility_code": "drop:text",
        "registered_by": "token:uuid",
        "title": "drop:text",
    },
    "EditionSealed": {
        "content_hash": "drop:text",
        "edition_id": "token:uuid",
        "license": "drop:text",
        "occurred_at": "keep:time",
        "publication_year": "keep:number",
        "publisher_facility_code": "drop:text",
        "sealed_by": "token:uuid",
        "sealed_dataset_ids": "token:uuid",
    },
    "EditionWithdrawn": {
        "edition_id": "token:uuid",
        "occurred_at": "keep:time",
        "withdrawal_reason": "drop:text",
        "withdrawn_by": "token:uuid",
    },
    "EnclosureDecommissioned": {
        "enclosure_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "triggered_by": "token:uuid",
    },
    "EnclosurePermitObserved": {
        "enclosure_id": "token:uuid",
        "from_status": "drop:text",
        "monitor_ref": "drop:text",
        "observed_at": "keep:time",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "to_status": "drop:text",
        "trigger": "drop:text",
        "triggered_by": "token:uuid",
    },
    "EnclosureRegistered": {
        "enclosure_id": "token:uuid",
        "facility_code": {"value": "drop:text"},
        "name": "drop:text",
        "occurred_at": "keep:time",
        "registered_by": "token:uuid",
    },
    "FacilityDecommissioned": {
        "decommissioned_by": "token:uuid",
        "facility_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "FacilityRegistered": {
        "alternate_identifiers": {
            "kind": "keep:enum:AlternateIdentifierKind",
            "value": "drop:text",
        },
        "code": {"value": "drop:text"},
        "display_name": "drop:text",
        "facility_id": "token:uuid",
        "kind": "keep:enum:FacilityKind",
        "occurred_at": "keep:time",
        "parent_id": "token:uuid",
        "registered_by": "token:uuid",
    },
    "FacilityTrustAnchorCredentialAdded": {
        "added_by": "token:uuid",
        "credential_id": "token:uuid",
        "facility_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "FacilityTrustAnchorCredentialRemoved": {
        "credential_id": "token:uuid",
        "facility_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "removed_by": "token:uuid",
    },
    "FamilyDefined": {
        "affordances": "keep:enum:Affordance",
        "family_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
    },
    "FamilyDeprecated": {
        "family_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "FamilyPresentsAsAdded": {
        "family_id": "token:uuid",
        "occurred_at": "keep:time",
        "role_id": "token:uuid",
    },
    "FamilyPresentsAsRemoved": {
        "family_id": "token:uuid",
        "occurred_at": "keep:time",
        "role_id": "token:uuid",
    },
    "FamilySettingsSchemaUpdated": {
        "family_id": "token:uuid",
        "occurred_at": "keep:time",
        "settings_schema": "drop:opaque",
    },
    "FamilyVersioned": {
        "affordances": "keep:enum:Affordance",
        "family_id": "token:uuid",
        "occurred_at": "keep:time",
        "version_tag": "drop:text",
    },
    "FixturePersistentIdAssigned": {
        "fixture_id": "token:uuid",
        "occurred_at": "keep:time",
        "persistent_id_scheme": "drop:text",
        "persistent_id_value": "drop:text",
    },
    "FixtureRegistered": {
        "assembly_content_hash": "drop:text",
        "assembly_id": "token:uuid",
        "fixture_id": "token:uuid",
        "occurred_at": "keep:time",
        "parameter_overrides": "drop:opaque",
        "registered_by": "token:uuid",
        "slot_asset_bindings": {"asset_id": "token:uuid", "slot_name": "drop:text"},
        "surface_id": "token:uuid",
    },
    "FrameDecommissioned": {
        "frame_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "FramePlacementUpdated": {
        "frame_id": "token:uuid",
        "new_placement": {
            "parent_frame_id": "token:uuid",
            "reference_surface": "keep:enum:ReferenceSurface",
            "rx": "keep:number",
            "ry": "keep:number",
            "rz": "keep:number",
            "tol_rx": "keep:number",
            "tol_ry": "keep:number",
            "tol_rz": "keep:number",
            "tol_x": "keep:number",
            "tol_y": "keep:number",
            "tol_z": "keep:number",
            "units": "keep:enum:UnitSystem",
            "x": "keep:number",
            "y": "keep:number",
            "z": "keep:number",
        },
        "occurred_at": "keep:time",
        "survey": "drop:opaque",
    },
    "FrameRegistered": {
        "frame_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "parent_id": "token:uuid",
        "placement": {
            "parent_frame_id": "token:uuid",
            "reference_surface": "keep:enum:ReferenceSurface",
            "rx": "keep:number",
            "ry": "keep:number",
            "rz": "keep:number",
            "tol_rx": "keep:number",
            "tol_ry": "keep:number",
            "tol_rz": "keep:number",
            "tol_x": "keep:number",
            "tol_y": "keep:number",
            "tol_z": "keep:number",
            "units": "keep:enum:UnitSystem",
            "x": "keep:number",
            "y": "keep:number",
            "z": "keep:number",
        },
        "supersedes": {
            "predecessor_frame_id": "token:uuid",
            "transform_from_predecessor": {
                "parent_frame_id": "token:uuid",
                "reference_surface": "keep:enum:ReferenceSurface",
                "rx": "keep:number",
                "ry": "keep:number",
                "rz": "keep:number",
                "tol_rx": "keep:number",
                "tol_ry": "keep:number",
                "tol_rz": "keep:number",
                "tol_x": "keep:number",
                "tol_y": "keep:number",
                "tol_z": "keep:number",
                "units": "keep:enum:UnitSystem",
                "x": "keep:number",
                "y": "keep:number",
                "z": "keep:number",
            },
        },
    },
    "HoldClaimReleased": {
        "cause": "drop:text",
        "claim_id": "token:uuid",
        "decided_by_decision_id": "token:uuid",
        "occurred_at": "keep:time",
        "run_id": "token:uuid",
    },
    "LanguageModelApproved": {"language_model_id": "token:uuid", "occurred_at": "keep:time"},
    "LanguageModelDefined": {
        "archivability": "drop:text",
        "cost_basis": "drop:opaque",
        "data_tier": "drop:text",
        "endpoint_note": "drop:text",
        "language_model_id": "token:uuid",
        "model": "drop:text",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "provider": "drop:text",
        "served_via": "drop:text",
        "snapshot_pin": "drop:text",
    },
    "LanguageModelDeprecated": {
        "language_model_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "LanguageModelRetired": {
        "language_model_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "LanguageModelRetirementAnnounced": {
        "effective_at": "keep:time",
        "language_model_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "MethodDefined": {
        "capability_id": "token:uuid",
        "execution_pattern": "keep:enum:ExecutionPattern",
        "method_id": "token:uuid",
        "monotone_quality": "keep:number",
        "name": "drop:text",
        "needed_assembly_ids": "token:uuid",
        "needed_family_ids": "token:uuid",
        "needed_input_kinds": "drop:text",
        "needed_supplies": "drop:text",
        "occurred_at": "keep:time",
        "resumable_from_checkpoint": "keep:number",
    },
    "MethodDeprecated": {
        "method_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "MethodLaunchSpecUpdated": {
        "launch_spec": "drop:opaque",
        "method_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "MethodParametersSchemaUpdated": {
        "method_id": "token:uuid",
        "occurred_at": "keep:time",
        "parameters_schema": "drop:opaque",
    },
    "MethodRequiredRoleAdded": {
        "family_id": "token:uuid",
        "method_id": "token:uuid",
        "occurred_at": "keep:time",
        "optional": "keep:number",
        "required_ports": "drop:opaque",
        "role_kind": "token:uuid",
        "role_name": "drop:text",
    },
    "MethodRequiredRoleRemoved": {
        "method_id": "token:uuid",
        "occurred_at": "keep:time",
        "role_name": "drop:text",
    },
    "MethodVersioned": {
        "content_hash": "drop:text",
        "method_id": "token:uuid",
        "occurred_at": "keep:time",
        "version_tag": "drop:text",
    },
    "ModelDefined": {
        "declared_family_ids": "token:uuid",
        "manufacturer": {
            "identifier": {"value": "drop:text"},
            "identifier_type": "keep:enum:ManufacturerIdentifierType",
            "name": {"value": "drop:text"},
        },
        "model_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "part_number": "drop:text",
        "version_tag": "drop:text",
    },
    "ModelDeprecated": {
        "model_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "ModelFamilyAdded": {
        "family_id": "token:uuid",
        "model_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "ModelFamilyRemoved": {
        "family_id": "token:uuid",
        "model_id": "token:uuid",
        "occurred_at": "keep:time",
    },
    "ModelVersioned": {
        "declared_family_ids": "token:uuid",
        "manufacturer": {
            "identifier": {"value": "drop:text"},
            "identifier_type": "keep:enum:ManufacturerIdentifierType",
            "name": {"value": "drop:text"},
        },
        "model_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "part_number": "drop:text",
        "version_tag": "drop:text",
    },
    "MountAssetInstalled": {
        "asset_id": "token:uuid",
        "mount_id": "token:uuid",
        "occurred_at": "keep:time",
        "previously_installed_asset_id": "token:uuid",
    },
    "MountAssetUninstalled": {
        "asset_id": "token:uuid",
        "mount_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "MountDecommissioned": {
        "mount_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
    },
    "MountPlacementUpdated": {
        "mount_id": "token:uuid",
        "new_placement": {
            "parent_frame_id": "token:uuid",
            "reference_surface": "keep:enum:ReferenceSurface",
            "rx": "keep:number",
            "ry": "keep:number",
            "rz": "keep:number",
            "tol_rx": "keep:number",
            "tol_ry": "keep:number",
            "tol_rz": "keep:number",
            "tol_x": "keep:number",
            "tol_y": "keep:number",
            "tol_z": "keep:number",
            "units": "keep:enum:UnitSystem",
            "x": "keep:number",
            "y": "keep:number",
            "z": "keep:number",
        },
        "occurred_at": "keep:time",
        "survey": "drop:opaque",
    },
    "MountRegistered": {
        "drawing": {
            "number": "drop:text",
            "revision": "drop:text",
            "system": "keep:enum:DrawingSystem",
        },
        "mount_id": "token:uuid",
        "occurred_at": "keep:time",
        "parent_id": "token:uuid",
        "placement": {
            "parent_frame_id": "token:uuid",
            "reference_surface": "keep:enum:ReferenceSurface",
            "rx": "keep:number",
            "ry": "keep:number",
            "rz": "keep:number",
            "tol_rx": "keep:number",
            "tol_ry": "keep:number",
            "tol_rz": "keep:number",
            "tol_x": "keep:number",
            "tol_y": "keep:number",
            "tol_z": "keep:number",
            "units": "keep:enum:UnitSystem",
            "x": "keep:number",
            "y": "keep:number",
            "z": "keep:number",
        },
        "slot_code": "drop:text",
    },
    "PermitActivated": {
        "activated_by": "token:uuid",
        "occurred_at": "keep:time",
        "permit_id": "token:uuid",
    },
    "PermitDefined": {
        "abi_tier_floor": "keep:enum:AbiTier",
        "allowed_artifact_kinds": "drop:text",
        "allowed_credential_ids": "token:uuid",
        "allowed_payload_types": "drop:text",
        "defined_by": "token:uuid",
        "direction": "keep:enum:Direction",
        "expires_at": "keep:time",
        "occurred_at": "keep:time",
        "peer_facility_id": {"value": "drop:text"},
        "permit_id": "token:uuid",
        "terms": {
            "accepted_canonicalization_versions": "drop:text",
            "inbound_allowed_artifact_kinds": "drop:text",
            "onward_action_scope": "keep:enum:OnwardActionScope",
            "publisher_grant_correlation_handle": "drop:text",
            "read_scope": "keep:enum:ReadScope",
            "required_receipt_kinds": "keep:enum:ReceiptKind",
            "scopes": {"kind": "drop:text", "name": "drop:text", "qualifier": "drop:text"},
        },
    },
    "PermitResumed": {
        "occurred_at": "keep:time",
        "permit_id": "token:uuid",
        "resumed_by": "token:uuid",
    },
    "PermitRevoked": {
        "occurred_at": "keep:time",
        "permit_id": "token:uuid",
        "reason": "drop:text",
        "revoked_by": "token:uuid",
    },
    "PermitSuspended": {
        "occurred_at": "keep:time",
        "permit_id": "token:uuid",
        "reason": "drop:text",
        "suspended_by": "token:uuid",
    },
    "PlanDefaultParametersUpdated": {
        "default_parameters": "drop:opaque",
        "occurred_at": "keep:time",
        "plan_id": "token:uuid",
    },
    "PlanDefined": {
        "asset_families_snapshot": "drop:opaque",
        "asset_ids": "token:uuid",
        "method_id": "token:uuid",
        "method_needed_family_ids_snapshot": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "plan_id": "token:uuid",
        "practice_id": "token:uuid",
    },
    "PlanDeprecated": {"occurred_at": "keep:time", "plan_id": "token:uuid", "reason": "drop:text"},
    "PlanRoleBound": {
        "asset_id": "token:uuid",
        "occurred_at": "keep:time",
        "plan_id": "token:uuid",
        "role_name": "drop:text",
    },
    "PlanRoleUnbound": {
        "occurred_at": "keep:time",
        "plan_id": "token:uuid",
        "role_name": "drop:text",
    },
    "PlanVersioned": {
        "content_hash": "drop:text",
        "occurred_at": "keep:time",
        "plan_id": "token:uuid",
        "version_tag": "drop:text",
    },
    "PlanWireAdded": {
        "occurred_at": "keep:time",
        "plan_id": "token:uuid",
        "source_asset_id": "token:uuid",
        "source_port_name": "drop:text",
        "target_asset_id": "token:uuid",
        "target_port_name": "drop:text",
    },
    "PlanWireRemoved": {
        "occurred_at": "keep:time",
        "plan_id": "token:uuid",
        "source_asset_id": "token:uuid",
        "source_port_name": "drop:text",
        "target_asset_id": "token:uuid",
        "target_port_name": "drop:text",
    },
    "PolicyDefined": {
        "conduit_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "permitted_commands": "drop:text",
        "permitted_principal_ids": "token:uuid",
        "policy_id": "token:uuid",
        "surface_id": "token:uuid",
    },
    "PolicyGrantRevoked": {
        "occurred_at": "keep:time",
        "policy_id": "token:uuid",
        "principal_id": "token:uuid",
        "reason": "drop:text",
        "revoked_by": "token:uuid",
    },
    "PracticeDefined": {
        "method_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "practice_id": "token:uuid",
        "site_id": "token:uuid",
    },
    "PracticeDeprecated": {
        "occurred_at": "keep:time",
        "practice_id": "token:uuid",
        "reason": "drop:text",
    },
    "PracticeVersioned": {
        "occurred_at": "keep:time",
        "practice_id": "token:uuid",
        "version_tag": "drop:text",
    },
    "ProcedureAborted": {
        "actuation_kind": "drop:text",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "reason": "drop:text",
    },
    "ProcedureActivitiesLogbookOpened": {
        "kind": "drop:text",
        "logbook_id": "token:uuid",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "schema": {"description": "drop:text", "fields": "drop:opaque"},
    },
    "ProcedureCompleted": {
        "actuation_kind": "drop:text",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
    },
    "ProcedureDiagnosticLogbookOpened": {
        "kind": "drop:text",
        "logbook_id": "token:uuid",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "schema": {"description": "drop:text", "fields": "drop:opaque"},
    },
    "ProcedureHeld": {
        "actuation_kind": "drop:text",
        "decided_by_decision_id": "token:uuid",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "reason": "drop:text",
    },
    "ProcedureIterationEnded": {
        "advised_next_point": "drop:opaque",
        "advised_stop": "keep:number",
        "alternatives": "drop:text",
        "confidence": "keep:number",
        "confidence_source": "keep:enum:DecisionConfidenceSource",
        "converged": "keep:number",
        "iteration_index": "keep:number",
        "model_ref": "drop:text",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "reason": "drop:text",
        "reasoning": "drop:text",
    },
    "ProcedureIterationStarted": {
        "iteration_index": "keep:number",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
    },
    "ProcedureOutcomeLogbookOpened": {
        "kind": "drop:text",
        "logbook_id": "token:uuid",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "schema": {"description": "drop:text", "fields": "drop:opaque"},
    },
    "ProcedureRegistered": {
        "capability_id": "token:uuid",
        "kind": "drop:text",
        "max_consecutive_unconverged_iterations": "keep:number",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "parent_run_id": "token:uuid",
        "procedure_id": "token:uuid",
        "recipe_id": "token:uuid",
        "target_asset_ids": "token:uuid",
    },
    "ProcedureResumed": {
        "decided_by_decision_id": "token:uuid",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "re_establishment_boundary": "keep:number",
    },
    "ProcedureStarted": {"occurred_at": "keep:time", "procedure_id": "token:uuid"},
    "ProcedureTruncated": {
        "interrupted_at": "keep:time",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "reason": "drop:text",
    },
    "PublicationReceiptRecorded": {
        "content_hash": "drop:text",
        "home_artifact_id": "token:uuid",
        "home_stream_id": "token:uuid",
        "home_stream_type": "drop:text",
        "occurred_at": "keep:time",
        "permit_id": "token:uuid",
        "receipt_id": "token:uuid",
        "recorded_at": "keep:time",
    },
    "RatificationDenied": {
        "occurred_at": "keep:time",
        "ratification_id": "token:uuid",
        "reason": "drop:text",
    },
    "RatificationGranted": {"occurred_at": "keep:time", "ratification_id": "token:uuid"},
    "RatificationRequested": {
        "command_name": "drop:text",
        "consequence_class": "drop:text",
        "occurred_at": "keep:time",
        "ratification_id": "token:uuid",
        "requested_by": "token:uuid",
        "target_action_id": "token:uuid",
    },
    "RecipeDefined": {
        "capability_id": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "recipe_id": "token:uuid",
        "steps": {
            "address": "drop:text",
            "capture_name": "drop:text",
            "command": "drop:text",
            "criterion": "drop:opaque",
            "input_uris": "by-value",
            "name": "drop:text",
            "output_ref_name": "drop:text",
            "output_uri": "drop:text",
            "parameters": "drop:opaque",
            "params": "drop:opaque",
            "value": "by-value",
            "verify": "keep:number",
        },
    },
    "RecipeDeprecated": {
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "recipe_id": "token:uuid",
        "replaced_by_recipe_id": "token:uuid",
    },
    "RecipeExpansionRecorded": {
        "bindings": "drop:opaque",
        "bindings_hash": "drop:text",
        "capability_id": "token:uuid",
        "capability_version": "drop:text",
        "expansion_port_version": "drop:text",
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "recipe_id": "token:uuid",
        "recipe_version": "drop:text",
        "step_count": "keep:number",
        "steps_hash": "drop:text",
    },
    "RecipeVersioned": {
        "occurred_at": "keep:time",
        "recipe_id": "token:uuid",
        "steps": {
            "address": "drop:text",
            "capture_name": "drop:text",
            "command": "drop:text",
            "criterion": "drop:opaque",
            "input_uris": "by-value",
            "name": "drop:text",
            "output_ref_name": "drop:text",
            "output_uri": "drop:text",
            "parameters": "drop:opaque",
            "params": "drop:opaque",
            "value": "by-value",
            "verify": "keep:number",
        },
        "version_tag": "drop:text",
    },
    "ResolvedStepsRecorded": {
        "occurred_at": "keep:time",
        "procedure_id": "token:uuid",
        "resolved_steps": "drop:opaque",
        "step_count": "keep:number",
    },
    "RoleDefined": {
        "consumes": "drop:text",
        "docstring": "drop:text",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "optional_affordances": "keep:enum:Affordance",
        "produces": "drop:text",
        "required_affordances": "keep:enum:Affordance",
        "role_id": "token:uuid",
    },
    "RunAborted": {
        "actuation_kind": "drop:text",
        "decided_by_decision_id": "token:uuid",
        "occurred_at": "keep:time",
        "producing_job_id": "drop:text",
        "reason": "drop:text",
        "run_id": "token:uuid",
    },
    "RunAddedToCampaign": {
        "campaign_id": "token:uuid",
        "occurred_at": "keep:time",
        "run_id": "token:uuid",
    },
    "RunAdjusted": {
        "adjusted_by": "token:uuid",
        "decided_by_decision_id": "token:uuid",
        "effective_parameters": "drop:opaque",
        "occurred_at": "keep:time",
        "parameters_patch": "drop:opaque",
        "reason": "drop:text",
        "run_id": "token:uuid",
    },
    "RunCompleted": {
        "actuation_kind": "drop:text",
        "artifact_uri": "drop:text",
        "occurred_at": "keep:time",
        "producing_job_id": "drop:text",
        "run_id": "token:uuid",
    },
    "RunHeld": {
        "cause": "drop:text",
        "claim_id": "token:uuid",
        "decided_by_decision_id": "token:uuid",
        "occurred_at": "keep:time",
        "run_id": "token:uuid",
    },
    "RunObservationLogbookOpened": {
        "kind": "drop:text",
        "logbook_id": "token:uuid",
        "occurred_at": "keep:time",
        "run_id": "token:uuid",
        "schema": {"description": "drop:text", "fields": "drop:opaque"},
    },
    "RunRemovedFromCampaign": {
        "campaign_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "run_id": "token:uuid",
    },
    "RunResumed": {
        "decided_by_decision_id": "token:uuid",
        "occurred_at": "keep:time",
        "released_claim_id": "token:uuid",
        "run_id": "token:uuid",
    },
    "RunStarted": {
        "acknowledged_cautions": {
            "category": "drop:text",
            "caution_id": "token:uuid",
            "severity": "drop:text",
            "target_id": "token:uuid",
            "target_kind": "drop:text",
            "text_excerpt": "drop:text",
            "workaround_excerpt": "drop:text",
        },
        "campaign_id": "token:uuid",
        "conduct_mode": "keep:enum:ConductMode",
        "decided_by_decision_id": "token:uuid",
        "effective_parameters": "drop:opaque",
        "external_refs": "drop:opaque",
        "input_dataset_ids": "token:uuid",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "override_parameters": "drop:opaque",
        "pinned_calibration_ids": "token:uuid",
        "plan_id": "token:uuid",
        "raid": "drop:text",
        "run_id": "token:uuid",
        "subject_id": "token:uuid",
        "trigger_source": "drop:text",
    },
    "RunStopped": {
        "decided_by_decision_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "run_id": "token:uuid",
    },
    "RunTruncated": {
        "decided_by_decision_id": "token:uuid",
        "interrupted_at": "keep:time",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "run_id": "token:uuid",
    },
    "SealInitialized": {
        "facility_id": {"value": "drop:text"},
        "initialized_by": "token:uuid",
        "occurred_at": "keep:time",
        "offline_credential_id": "token:uuid",
        "online_credential_id": "token:uuid",
    },
    "SealOnlineKeyRotated": {
        "facility_id": {"value": "drop:text"},
        "new_online_credential_id": "token:uuid",
        "occurred_at": "keep:time",
        "rotated_by": "token:uuid",
        "signed_by_offline_root": "keep:number",
    },
    "SealPointerSigned": {
        "facility_id": {"value": "drop:text"},
        "head_hash": "drop:text",
        "occurred_at": "keep:time",
        "sequence_number": "keep:number",
        "signed_at": "keep:time",
        "signed_by": "token:uuid",
    },
    "SealRepublishingCompleted": {
        "completed_by": "token:uuid",
        "facility_id": {"value": "drop:text"},
        "new_head_hash": "drop:text",
        "new_sequence_number": "keep:number",
        "occurred_at": "keep:time",
    },
    "SealRepublishingStarted": {
        "facility_id": {"value": "drop:text"},
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "started_by": "token:uuid",
    },
    "SubjectDiscarded": {
        "discarded_by": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "subject_id": "token:uuid",
    },
    "SubjectDismounted": {
        "dismounted_by": "token:uuid",
        "from_asset_id": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "subject_id": "token:uuid",
    },
    "SubjectMeasured": {
        "measured_by": "token:uuid",
        "occurred_at": "keep:time",
        "subject_id": "token:uuid",
    },
    "SubjectMounted": {
        "asset_id": "token:uuid",
        "mounted_by": "token:uuid",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "subject_id": "token:uuid",
    },
    "SubjectRegistered": {
        "name": "drop:text",
        "occurred_at": "keep:time",
        "registered_by": "token:uuid",
        "subject_id": "token:uuid",
    },
    "SubjectRemoved": {
        "occurred_at": "keep:time",
        "removed_by": "token:uuid",
        "subject_id": "token:uuid",
    },
    "SubjectReturned": {
        "occurred_at": "keep:time",
        "returned_by": "token:uuid",
        "subject_id": "token:uuid",
    },
    "SubjectStored": {
        "occurred_at": "keep:time",
        "stored_by": "token:uuid",
        "subject_id": "token:uuid",
    },
    "SupplyDegraded": {
        "from_status": "drop:text",
        "monitor_ref": "drop:text",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "supply_id": "token:uuid",
        "trigger": "drop:text",
        "triggered_by": "token:uuid",
    },
    "SupplyDeregistered": {
        "from_status": "drop:text",
        "monitor_ref": "drop:text",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "supply_id": "token:uuid",
        "trigger": "drop:text",
        "triggered_by": "token:uuid",
    },
    "SupplyMarkedAvailable": {
        "from_status": "drop:text",
        "monitor_ref": "drop:text",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "supply_id": "token:uuid",
        "trigger": "drop:text",
        "triggered_by": "token:uuid",
    },
    "SupplyMarkedRecovering": {
        "from_status": "drop:text",
        "monitor_ref": "drop:text",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "supply_id": "token:uuid",
        "trigger": "drop:text",
        "triggered_by": "token:uuid",
    },
    "SupplyMarkedUnavailable": {
        "from_status": "drop:text",
        "monitor_ref": "drop:text",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "supply_id": "token:uuid",
        "trigger": "drop:text",
        "triggered_by": "token:uuid",
    },
    "SupplyRegistered": {
        "containing_asset_id": "token:uuid",
        "facility_code": {"value": "drop:text"},
        "kind": "drop:text",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "supply_id": "token:uuid",
        "trigger": "drop:text",
        "triggered_by": "token:uuid",
    },
    "SupplyRestored": {
        "from_status": "drop:text",
        "monitor_ref": "drop:text",
        "occurred_at": "keep:time",
        "reason": "drop:text",
        "supply_id": "token:uuid",
        "trigger": "drop:text",
        "triggered_by": "token:uuid",
    },
    "SurfaceDefined": {
        "kind": "keep:enum:SurfaceKind",
        "name": "drop:text",
        "occurred_at": "keep:time",
        "surface_id": "token:uuid",
    },
    "VisitAborted": {"occurred_at": "keep:time", "reason": "drop:text", "visit_id": "token:uuid"},
    "VisitArrived": {"occurred_at": "keep:time", "visit_id": "token:uuid"},
    "VisitCancelled": {"occurred_at": "keep:time", "reason": "drop:text", "visit_id": "token:uuid"},
    "VisitCheckedIn": {
        "actor_id": "token:uuid",
        "mode": "drop:text",
        "occurred_at": "keep:time",
        "visit_id": "token:uuid",
    },
    "VisitCheckedOut": {
        "actor_id": "token:uuid",
        "occurred_at": "keep:time",
        "visit_id": "token:uuid",
    },
    "VisitCompleted": {"occurred_at": "keep:time", "visit_id": "token:uuid"},
    "VisitHeld": {"occurred_at": "keep:time", "reason": "drop:text", "visit_id": "token:uuid"},
    "VisitPresenceClosed": {
        "actor_id": "token:uuid",
        "occurred_at": "keep:time",
        "visit_id": "token:uuid",
    },
    "VisitRegistered": {
        "external_refs": {"scheme": "drop:text", "value": "drop:text"},
        "occurred_at": "keep:time",
        "parent_id": "token:uuid",
        "planned_end_at": "keep:time",
        "planned_start_at": "keep:time",
        "policy_id": "token:uuid",
        "surface_id": "token:uuid",
        "type": "drop:text",
        "visit_id": "token:uuid",
    },
    "VisitResumed": {"occurred_at": "keep:time", "visit_id": "token:uuid"},
    "VisitStarted": {"occurred_at": "keep:time", "visit_id": "token:uuid"},
    "VisitSurfaceControlReleased": {
        "occurred_at": "keep:time",
        "surface_id": "token:uuid",
        "visit_id": "token:uuid",
    },
    "VisitSurfaceControlTaken": {
        "occurred_at": "keep:time",
        "surface_id": "token:uuid",
        "visit_id": "token:uuid",
    },
    "VisitVoided": {"occurred_at": "keep:time", "reason": "drop:text", "visit_id": "token:uuid"},
    "ZoneDefined": {"name": "drop:text", "occurred_at": "keep:time", "zone_id": "token:uuid"},
}
