"""Clearance aggregate: state, enums (status / kind), bindings, errors, events, evolver, read repo.

Vertical slices that operate on this aggregate live under
`cora.safety.features.<verb>_clearance/` and import from here for state
and event types.

Public surface: enums + VOs + bindings + errors + events + evolver +
load_clearance. 11a-a ships the genesis (Defined-only); 11a-b adds the
6 FSM-closure events + slices; 11a-c adds the 3 terminal/amendment
events + slices.
"""

from cora.safety.aggregates.clearance.events import (
    ClearanceActivated,
    ClearanceApproved,
    ClearanceEvent,
    ClearanceExpired,
    ClearanceRegistered,
    ClearanceRejected,
    ClearanceReviewStarted,
    ClearanceReviewStepAppended,
    ClearanceSubmitted,
    ClearanceSuperseded,
    event_type_name,
    from_stored,
    to_payload,
)
from cora.safety.aggregates.clearance.evolver import evolve, fold
from cora.safety.aggregates.clearance.read import load_clearance
from cora.safety.aggregates.clearance.state import (
    CLEARANCE_EXTERNAL_ID_MAX_LENGTH,
    CLEARANCE_HAZARD_NOTES_MAX_LENGTH,
    CLEARANCE_MITIGATION_REF_MAX_LENGTH,
    CLEARANCE_REVIEWER_NOTES_MAX_LENGTH,
    CLEARANCE_REVIEWER_ROLE_MAX_LENGTH,
    CLEARANCE_TITLE_MAX_LENGTH,
    AssetBinding,
    Clearance,
    ClearanceAlreadyExistsError,
    ClearanceBinding,
    ClearanceCannotActivateError,
    ClearanceCannotAmendError,
    ClearanceCannotAppendReviewStepError,
    ClearanceCannotApproveError,
    ClearanceCannotExpireError,
    ClearanceCannotRejectError,
    ClearanceCannotStartReviewError,
    ClearanceCannotSubmitError,
    ClearanceFacilityNotFoundError,
    ClearanceNotFoundError,
    ClearanceStatus,
    ClearanceTitle,
    ExternalRefBinding,
    HazardDeclaration,
    InvalidClearanceBindingsError,
    InvalidClearanceDeclarationTargetError,
    InvalidClearanceExpireReasonError,
    InvalidClearanceExternalIdError,
    InvalidClearanceHazardNotesError,
    InvalidClearanceMitigationRefError,
    InvalidClearanceRejectReasonError,
    InvalidClearanceReviewerNotesError,
    InvalidClearanceReviewerRoleError,
    InvalidClearanceReviewStepDecidedAtError,
    InvalidClearanceReviewStepIndexError,
    InvalidClearanceTitleError,
    InvalidClearanceValidityWindowError,
    ProcedureBinding,
    ReviewStep,
    RunBinding,
    SubjectBinding,
)

__all__ = [
    "CLEARANCE_EXTERNAL_ID_MAX_LENGTH",
    "CLEARANCE_HAZARD_NOTES_MAX_LENGTH",
    "CLEARANCE_MITIGATION_REF_MAX_LENGTH",
    "CLEARANCE_REVIEWER_NOTES_MAX_LENGTH",
    "CLEARANCE_REVIEWER_ROLE_MAX_LENGTH",
    "CLEARANCE_TITLE_MAX_LENGTH",
    "AssetBinding",
    "Clearance",
    "ClearanceActivated",
    "ClearanceAlreadyExistsError",
    "ClearanceApproved",
    "ClearanceBinding",
    "ClearanceCannotActivateError",
    "ClearanceCannotAmendError",
    "ClearanceCannotAppendReviewStepError",
    "ClearanceCannotApproveError",
    "ClearanceCannotExpireError",
    "ClearanceCannotRejectError",
    "ClearanceCannotStartReviewError",
    "ClearanceCannotSubmitError",
    "ClearanceEvent",
    "ClearanceExpired",
    "ClearanceFacilityNotFoundError",
    "ClearanceNotFoundError",
    "ClearanceRegistered",
    "ClearanceRejected",
    "ClearanceReviewStarted",
    "ClearanceReviewStepAppended",
    "ClearanceStatus",
    "ClearanceSubmitted",
    "ClearanceSuperseded",
    "ClearanceTitle",
    "ExternalRefBinding",
    "HazardDeclaration",
    "InvalidClearanceBindingsError",
    "InvalidClearanceDeclarationTargetError",
    "InvalidClearanceExpireReasonError",
    "InvalidClearanceExternalIdError",
    "InvalidClearanceHazardNotesError",
    "InvalidClearanceMitigationRefError",
    "InvalidClearanceRejectReasonError",
    "InvalidClearanceReviewStepDecidedAtError",
    "InvalidClearanceReviewStepIndexError",
    "InvalidClearanceReviewerNotesError",
    "InvalidClearanceReviewerRoleError",
    "InvalidClearanceTitleError",
    "InvalidClearanceValidityWindowError",
    "ProcedureBinding",
    "ReviewStep",
    "RunBinding",
    "SubjectBinding",
    "event_type_name",
    "evolve",
    "fold",
    "from_stored",
    "load_clearance",
    "to_payload",
]
