"""Asset aggregate: state, level/lifecycle enums, errors, events, evolver, read repo.

Vertical slices that operate on this aggregate live under
`cora.equipment.features.<verb>_asset/` and import from here for
state and event types.
"""

from cora.equipment.aggregates.asset.events import (
    AssetActivated,
    AssetDecommissioned,
    AssetDegraded,
    AssetEvent,
    AssetFamilyAdded,
    AssetFamilyRemoved,
    AssetFaulted,
    AssetMaintenanceEntered,
    AssetMaintenanceExited,
    AssetPortAdded,
    AssetPortRemoved,
    AssetRegistered,
    AssetRelocated,
    AssetRestored,
    AssetSettingsUpdated,
    event_type_name,
    from_stored,
    to_payload,
)
from cora.equipment.aggregates.asset.evolver import evolve, fold
from cora.equipment.aggregates.asset.read import load_asset
from cora.equipment.aggregates.asset.state import (
    ASSET_NAME_MAX_LENGTH,
    PORT_NAME_MAX_LENGTH,
    PORT_SIGNAL_TYPE_MAX_LENGTH,
    Asset,
    AssetAlreadyExistsError,
    AssetCannotActivateError,
    AssetCannotAddFamilyError,
    AssetCannotAddPortError,
    AssetCannotDecommissionError,
    AssetCannotEnterMaintenanceError,
    AssetCannotExitMaintenanceError,
    AssetCannotRelocateError,
    AssetCannotRemoveFamilyError,
    AssetCannotRemovePortError,
    AssetCondition,
    AssetLevel,
    AssetLifecycle,
    AssetModelMismatch,
    AssetName,
    AssetNotFoundError,
    AssetPort,
    InvalidAssetNameError,
    InvalidAssetParentError,
    InvalidAssetPortNameError,
    InvalidAssetPortSignalTypeError,
    InvalidAssetSettingsError,
    PortDirection,
)

__all__ = [
    "ASSET_NAME_MAX_LENGTH",
    "PORT_NAME_MAX_LENGTH",
    "PORT_SIGNAL_TYPE_MAX_LENGTH",
    "Asset",
    "AssetActivated",
    "AssetAlreadyExistsError",
    "AssetCannotActivateError",
    "AssetCannotAddFamilyError",
    "AssetCannotAddPortError",
    "AssetCannotDecommissionError",
    "AssetCannotEnterMaintenanceError",
    "AssetCannotExitMaintenanceError",
    "AssetCannotRelocateError",
    "AssetCannotRemoveFamilyError",
    "AssetCannotRemovePortError",
    "AssetCondition",
    "AssetDecommissioned",
    "AssetDegraded",
    "AssetEvent",
    "AssetFamilyAdded",
    "AssetFamilyRemoved",
    "AssetFaulted",
    "AssetLevel",
    "AssetLifecycle",
    "AssetMaintenanceEntered",
    "AssetMaintenanceExited",
    "AssetModelMismatch",
    "AssetName",
    "AssetNotFoundError",
    "AssetPort",
    "AssetPortAdded",
    "AssetPortRemoved",
    "AssetRegistered",
    "AssetRelocated",
    "AssetRestored",
    "AssetSettingsUpdated",
    "InvalidAssetNameError",
    "InvalidAssetParentError",
    "InvalidAssetPortNameError",
    "InvalidAssetPortSignalTypeError",
    "InvalidAssetSettingsError",
    "PortDirection",
    "event_type_name",
    "evolve",
    "fold",
    "from_stored",
    "load_asset",
    "to_payload",
]
